### ISSUE TITLE
Problem using got in aws

### ISSUE THREAD

**Issue by rafaelgavabarreto** [sindresorhus/got#1020]
#### Describe the bug

 - Node.js version: node:8.9-alpine
 - OS & version: aws-cli/1.16.115 Python/3.6.7 Linux/4.14.152-98.182.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.12.105

#### Actual behavior
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:209:11)
    at Object.<anonymous> (/usr/src/app/node_modules/got/dist/source/get-response.js:8:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/got/dist/source/request-as-event-emitter.js:13:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
...

#### Expected behavior

...

#### Code to reproduce

```js
                         (async () => {
                            const { body: html, url } = await got(item.link)
                            const metadata = await metascraper({ html, url })
                            urlImage = metadata.image
                         })();
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Node 8 is no longer supported.

**Comment by abranhe** [comment]
Got the same issue! @szmarczak answer explains a lot. Upgrading from Node.js 8 fixed all.

```diff
language: node_js
node_js:
-  - "8"
+  - "10"
```
