### ISSUE TITLE
Special character in url throwing 404

### ISSUE THREAD

**Issue by vatsaljrathod** [sindresorhus/got#1024]
#### Describe the bug

 - Node.js version: 12.9.0
 - OS & version: MacOs Cataina 10.15.2
 - Got version: 10.2.2

Special characters in URL throwing 404 response. 

#### Actual behavior
```
HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/divyeshpatel/Development/test/node_modules/got/dist/source/as-promise.js:108:31)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) æ
  name: 'HTTPError'
```

#### Expected behavior
No 404, it should be 200. I can able to get the response(200) on the same URL with request lib.

#### Code to reproduce

```js
var got = require('got'),
    fs  = require('fs');
(async () => {
	try {
    // let url = 'https://demo.gumlet.com/lemon.jpeg';
    // let url = 'https://hindiraj.com/wp-content/uploads/2019/10/à¤ªà¥à¤¸à¥à¤à¤¸-PCS-à¤ªà¤°à¥à¤à¥à¤·à¤¾-à¤à¥-à¤¤à¥à¤¯à¤¾à¤°à¥-à¤à¥à¤¸à¥-à¤à¤°à¥_-1.png';
    let url ='https://salakconsulting.co.uk/wp-content/uploads/2019/12/Certificate-for-radosÅaw-Salak.jpg';
    const response = await got(url, {encoding: 'binary'});
    fs.writeFileSync('download.jpg', response.body, 'binary');

	} catch (error) {
                console.log(error);
		//=> '404 error'
	}
})();
```

Here is a similar snippet with the help of the request library.

```js
var request = require('request'),
        fs  = require('fs');
 // let url = 'https://demo.gumlet.com/lemon.jpeg';
 // let url = 'https://hindiraj.com/wp-content/uploads/2019/10/à¤ªà¥à¤¸à¥à¤à¤¸-PCS-à¤ªà¤°à¥à¤à¥à¤·à¤¾-à¤à¥-à¤¤à¥à¤¯à¤¾à¤°à¥-à¤à¥à¤¸à¥-à¤à¤°à¥_-1.png';
 let url ='https://salakconsulting.co.uk/wp-content/uploads/2019/12/Certificate-for-radosÅaw-Salak.jpg';

 request(url, {encoding: 'binary'}, function(error, response, body) {
   fs.writeFile('download.jpg', body, 'binary', function (err) {});
 });

```

Any URL without any special character is working fine.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The URL is not properly encoded. You're not looking for `Å�` but `ł`.

**Comment by adityapatadia** [comment]
Hi,
Even this is not working.

```javascript

var got = require('got'),
    fs  = require('fs');
(async () => {
	try {
    // let url = 'https://demo.gumlet.com/lemon.jpeg';
    let url ='https://salakconsulting.co.uk/wp-content/uploads/2019/12/Certificate-for-radosław-Salak.jpg';
    const response = await got(encodeURI(url), {encoding: 'binary'});
    fs.writeFileSync('download.jpg', response.body, 'binary');

	} catch (error) {
                console.log(error);
		//=> '404 error'
	}
})();

```

The problem we face is that the URL is not under our control. Our clients provide the URL from which we need to fetch images. I am not be expert on handling special characters so any tips will be helpful.

**Comment by szmarczak** [comment]
The URL is already gone. Sorry, but this is NOT a good place for JavaScript tutoring.

**Comment by adityapatadia** [comment]
Sounds fine. It would still be great if you can point why it was working with `request` and did not work with `got`.

**Comment by adityapatadia** [comment]
Nevermind, the issue was that PHP was creating problem in URL encode. No issues in GOT.
