### ISSUE TITLE
options.username | password isn't working the same as options.auth worked. [URIError: URI malformed]

### ISSUE THREAD

**Issue by dsafanyuk** [sindresorhus/got#1029]
#### Describe the bug

 - Node.js version: v12.13.1 & v13
 - OS & version: MacOS 10.15.2

#### Actual behavior

Setting `options.username/password` seems to have no effect.
```
URIError: URI malformed
    at decodeURI (<anonymous>)
    at Object.exports.normalizeRequestArguments (/Users/api/node_modules/got/dist/source/normalize-arguments.js:350:5)
    at async get (api/node_modules/got/dist/source/request-as-event-emitter.js:43:27)
    at async /api/node_modules/got/dist/source/request-as-event-emitter.js:258:13
```
#### Expected behavior

create an Authorization header like `options.auth` did previously.

#### Code to reproduce

```js
const myURL = new URL(
        `https://product.com/some/path/here`
    );
try 
     await got.post( {
                     url: myURL,
                     throwHttpErrors: false,
                     rejectUnauthorized: false,
                     username: user,
                     password: pass,
                     json: {
                            someData: "here",
                     },
                     followRedirect: true, // Could the issue be due to a redirect?
            })

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

Sorry this is one of my first issues on GH, please let me know if can clear anything up.

**Comment by dsafanyuk** [comment]
AHA! I found the issue.

my `pass` had a `%` and that was giving me the issue.

the fix:

```
await got.post( {
                     url: myURL,
                     throwHttpErrors: false,
                     rejectUnauthorized: false,
                     username: user,
                     password: encodeURI(pass), // this corrects the problem
                     json: {
                            someData: "here",
                     },
                     followRedirect: true, 
            })
```

**Comment by yovanoc** [comment]
Hello, I have a question, username and password are just for Basic Auth, or there is a way to use digest auth or things like that?

**Comment by szmarczak** [comment]
> or there is a way to use digest auth or things like that?

You can specify the `Auth` header.
