### ISSUE TITLE
GOT require issue

### ISSUE THREAD

**Issue by khizarsonu** [sindresorhus/got#1084]
#### Describe the bug

 - Node.js version: 8.17.0
 - OS & version: macos

#### Actual behavior
gives below error
/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
...

#### Expected behavior
console.log should print object information about got 
...

#### Code to reproduce

```js
const got = require('got');
console.log(got);
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by khizarsonu** [comment]
as i see got works fine in node 12+ , in case got does not support older version on nodejs, then please highlight and mention it in the documentation.
this will save a lot of time of developer facing similar issue

**Comment by sindresorhus** [comment]
Got already indicates the required Node.js version in package.json

**Comment by dhamodharan99** [comment]
I ran the following command on 2 versions.

npm install -g bootprint
npm install -g bootprint-openapi
bootprint openapi http://petstore.swagger.io/v2/swagger.json target
bootprint openapi http://petstore.swagger.io/v2/swagger.json openapi

With node version v8.9.1, this is not working. With the node version v10.16.3 the above codes are working.
(
![image](https://user-images.githubusercontent.com/4477473/81268723-eec1db00-9065-11ea-99ee-cb17a9e23ccb.png) )

**Comment by huydox** [comment]
I got the same error in NodeJS v15.14.0 and latest Got

`/node_modules/got/dist/source/create.js:157
      const paginateEach = (async function* (url, options) {
                                          ^

  SyntaxError: Unexpected token *
      at createScript (vm.js:80:10)
      at Object.runInThisContext (vm.js:139:10)
      at Module._compile (module.js:606:28)
      at Object.Module._extensions..js (module.js:653:10)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/huydo/Dev/CorpTek/cardioscope-desktop-electron/node_modules/got/dist/source/index.js:14:18)`
