### ISSUE TITLE
RequestError: The "listener" argument must be of type function. Received an instance of Object

### ISSUE THREAD

**Issue by Shahriar87** [sindresorhus/got#1109]
#### What would you like to discuss?

Getting this error when trying to make a got.post request.

```
RequestError: The "listener" argument must be of type function. Received an instance of Object
    at get (/app/node_modules/got/dist/source/request-as-event-emitter.js:208:27)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at checkListener (events.js:109:11)
    at ClientRequest.once (events.js:431:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.<anonymous> (/app/node_modules/https-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at makeRequest (/app/node_modules/newrelic/lib/instrumentation/core/http.js:505:22)
    at instrumentRequest (/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:112:21)
    at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at Tracer.addSegment (/app/node_modules/newrelic/lib/transaction/tracer/index.js:83:48)
    at instrumentOutbound (/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:62:23)
    at Object.wrappedRequest (/app/node_modules/newrelic/lib/instrumentation/core/http.js:503:12)
    at get (/app/node_modules/got/dist/source/request-as-event-emitter.js:205:65)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
```
...

#### Checklist
This is how I am making a request:

```
    const defaults = {
        headers: {
            'Content-Type': 'application/json'
        },
        timeout: 500,
        retry: {
            limit: 3
        },
        hooks: {
            beforeError: [
                err => {
                    // do something
                    return err;
                }
            ],
            beforeRetry: [
                (options, error, retryCount) => {
                    if (options.url) {
                        console.log(`Failed on ${options.url.href} for ${error.name}, Retry count ${retryCount}`)
                    }
                },
            ]
        }
    };
    const extended = got.extend(defaults);
    extended.post(url, {json: body});
```

Node version is v12.16.1

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
I cannot reproduce: https://runkit.com/szmarczak/5e6734ac28a3cd001a7a1255

**Comment by Shahriar87** [comment]
Found the issue was newrelic related. Upgrading the newrelic version to latest fixed the issue.

**Comment by Daghall** [comment]
We had the same problem with an old version on Nock. It took a while to find.

**Comment by mapsam** [comment]
👋 chiming in to thank @Daghall for mentioning [nock](https://github.com/nock/nock) - had the same issue. Upgraded from v10.x to v13.x and issues are resolved. Cheers!

**Comment by rocketmaniac** [comment]
I get the same error as the OP even with:

"got": "^11.8.2",
"newrelic": "^8.1.0",

nock does not even appear in my yarn.lock file
