### ISSUE TITLE
Memory leak when using `cache`

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/got#1128]
#### Describe the bug

 - Node.js version: `v12.16.1`
 - OS & version: `macOS 10.15.3`

#### Actual behavior
Getting the following error message when making multiple requests with `got`:

> (node:60669) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [KeyvMemcache]. Use emitter.setMaxListeners() to increase limit

#### Expected behavior
For got/keyv to:
  - not keep adding the event listener for each call, leading to the memory leak
  - clean up the event listener (can add a teardown feature req in Keyv)

I expect this behavior especially when `.extend`ing:
```
const extendedGot = got.extend({ cache });
```

#### Code to reproduce
- I traced it back to [keyv:L43](https://github.com/lukechilds/keyv/blob/master/src/index.js#L43)
- The cache storage is passed into `got`, and `got` passes that into `Keyv`, which adds the event listener
- In the code below, I shim `.on`, but in practice I'm using [keyv-memcache](https://github.com/jaredwray/keyv-memcache), which extends the EventEmitter which is what makes the warning about the memory leak

```js
const got = require('got');

const cache = new Map();
cache.on = function(eventName) {
	console.trace(eventName);
};

// Individual calls
for (let i = 0; i < 10; i++) {
	got('http://google.com', { cache });
}

// Extended calls
const extendedGot = got.extend({ cache });
for (let i = 0; i < 10; i++) {
	extendedGot('http://google.com');
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

For what it's worth, I also read https://github.com/sindresorhus/got/issues/792, https://github.com/lukechilds/cacheable-request/issues/30, and https://github.com/sindresorhus/got/pull/921 (the "click for solution" link is broken for me) but I believe the problem is different.

**Comment by szmarczak** [comment]
You're creating a new Keyv instance every time (using the `cacheable-request` package unknowingly).

**Comment by szmarczak** [comment]
@sindresorhus I think we should disallow passing raw storage instances and force users to pass a `Keyv` instance.

**Comment by sindresorhus** [comment]
> I think we should disallow passing raw storage instances and force users to pass a Keyv instance.

That's inconvenient for users just wanting a simple memory cache. Can we not just handle it somehow?

**Comment by szmarczak** [comment]
> Can we not just handle it somehow?

It can be solved on the Keyv side via a WeakMap.

**Comment by privatenumber** [comment]
A destructor/destroy method can also be added in Keyv that takes care of tear-downs.

**Comment by szmarczak** [comment]
Actually I can solve this in Got, then this issue would be fixed as well as #1098

**Comment by szmarczak** [comment]
This should be fixed in 2abacfffef9e84afd111827bb7848815e28b0cbf but somehow I still get the warning...

**Comment by szmarczak** [comment]
Interestingly if you put `await` before `got(...)` it works as expected...

**Comment by szmarczak** [comment]
The script now gives (I replaced `console.trace` with `console.log` and ran `node --trace-warnings bug.js`):

```
error
(node:24387) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Keyv]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at Keyv.addListener (events.js:406:10)
    at Keyv.once (events.js:437:8)
    at /home/szm/Desktop/got/node_modules/cacheable-request/src/index.js:190:16
    at /home/szm/Desktop/got/node_modules/cacheable-request/src/index.js:202:6
    at /home/szm/Desktop/got/dist/source/core/index.js:62:59
    at new Promise (<anonymous>)
    at cacheFn (/home/szm/Desktop/got/dist/source/core/index.js:56:41)
    at PromisableRequest._makeRequest (/home/szm/Desktop/got/dist/source/core/index.js:881:39)
    at /home/szm/Desktop/got/dist/source/core/index.js:291:28
```

It just attaches `keyv.once('error', ...)` but it's removed when the cache has been read.

**Comment by szmarczak** [comment]
Related: https://github.com/lukechilds/keyv/issues/101

**Comment by Rumatoid** [comment]
memory leak
```js
const map = new Map();

let response = await got('https://www.youtube.com', { cache: map });

for (let i = 0; i < 1000; i++)
    response = await got('https://www.youtube.com', { cache: map });
```

**Comment by GalRab** [comment]
It seems to be fix in [cacheable-request version 10.2.6](https://github.com/jaredwray/cacheable-request/issues/222)
Could you please update cacheable-request to version 10.2.6?
