### ISSUE TITLE
Unix sockets don't support "body"

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/got#1194]
#### Describe the bug

 - Node.js version: v13.12.0
 - OS & version: Unraid beta 8

#### Actual behavior
```
 GotError: The "source" argument must be of type function or an instance of Stream, Iterable, or AsyncIterable. Received undefined
    at onError (/usr/local/node/graphql-api/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/usr/local/node/graphql-api/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at pipeline (internal/streams/pipeline.js:208:15)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at pipeline (internal/util.js:296:12)
    at handleRequest (/usr/local/node/graphql-api/node_modules/got/dist/source/request-as-event-emitter.js:165:23)
    at get (/usr/local/node/graphql-api/node_modules/got/dist/source/request-as-event-emitter.js:197:17)
    at /usr/local/node/graphql-api/node_modules/got/dist/source/request-as-event-emitter.js:264:13 {
  name: 'RequestError',
  code: 'ERR_INVALID_ARG_TYPE'
}
```

When trying this against any **HTTP** endpoint the request works as expected.

#### Expected behavior
No error and the request to finish.

#### Code to reproduce
Removing the `body` options stops the error being thrown.

```ts
import got from 'got';
got.post('unix:/var/run/graphql-api.sock:/graphql', {
    headers: {
        'x-api-key': 'test123'
    },
    body: 'this is the body'
}).then(console.info).catch(console.error);
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by OmgImAlexis** [comment]
This works with requests for example.

```ts
const request = require('request');

request.post('http://unix:/var/run/graphql-api.sock:/graphql', {
    headers: {
        'x-api-key': 'test123'
    },
    body: 'this is the body'
}, (error, response) => {
    if (error) {
        console.error(error);
    }
    console.info(response);
});
```

**Comment by szmarczak** [comment]
You're using an outdated version of Got. Please try upgrading to Got 11.
