### ISSUE TITLE
Throws `RequestError: setTimeout(...).unref is not a function` in Electron

### ISSUE THREAD

**Issue by kaatt** [sindresorhus/got#1219]
#### Describe the bug

 - Node.js version: 12.13.0
 - OS & version: macOS 10.15.4
 - Electron version: 8.2.5
 - Got version: 11.1.0

#### Actual behavior

Running `require('got')({ url: 'http://example.com/' })` in the console throws:
```
Uncaught (in promise) RequestError: setTimeout(...).unref is not a function
    at ClientRequest.<anonymous> (/private/var/folders/qp/tmp/T/tmp/node_modules/got/dist/source/core/index.js:786:25)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/private/var/folders/qp/tmp/T/tmp/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at CacheableLookup.tick (/private/var/folders/qp/tmp/T/tmp/node_modules/cacheable-lookup/source/index.js:290:22)
    at CacheableLookup.query (/private/var/folders/qp/tmp/T/tmp/node_modules/cacheable-lookup/source/index.js:176:8)
    at CacheableLookup.lookupAsync (/private/var/folders/qp/tmp/T/tmp/node_modules/cacheable-lookup/source/index.js:137:27)
    at CacheableLookup.lookup (/private/var/folders/qp/tmp/T/tmp/node_modules/cacheable-lookup/source/index.js:121:8)
    at net.js:1030:5
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12)
    at lookupAndConnect (net.js:1029:3)
    at Socket.connect (net.js:963:5)
    at Agent.connect [as createConnection] (net.js:172:17)
    at Agent.createSocket (_http_agent.js:234:26)
```

This can be reproduced with Electron Fiddle: https://www.electronjs.org/fiddle in the renderer process code or entering it directly in the console.

<img width="433" alt="" src="https://user-images.githubusercontent.com/10688522/80925741-eccef200-8daf-11ea-9aa6-9c413de3b79c.png">

**Comment by kaatt** [comment]
Seems like a DNS issue. `require('got')({ url: 'https://1.1.1.1/' })` works.

**Comment by szmarczak** [comment]
Fixed in `cacheable-lookup`

**Comment by kaatt** [comment]
Will a new got version come out or should I manually pin `cacheable-lookup`?
