### ISSUE TITLE
Throw more useful errors for request validation

### ISSUE THREAD

**Issue by alechirsch** [sindresorhus/got#1257]
#### What problem are you trying to solve?

I passed in searchParams option as null and got back an error that looks like this:
```
TypeError: Expected value which is `predicate returns truthy for any value`, received value of type `Array`.
```

It took some  time to figure out why I was getting this error, I had to put a breakpoint on where that error was thrown, and then look at the callstack of the error that was passed to that function to figure out what was wrong.

Would it be possible to add to the error message saying that the option `searchParams` (or another option) is the wrong type? It would be much clearer and help with debugging.

**Comment by szmarczak** [comment]
I knew someone would raise an issue about this someday... See https://github.com/sindresorhus/is/issues/107

**Comment by stephenmathieson** [comment]
Currently dealing with this.

<details>
<summary>Error log</summary>

```json
{
  "error": "Expected value which is `predicate returns truthy for any value`, received values of types `string`.",
  "stack": "TypeError: Expected value which is `predicate returns truthy for any value`, received values of types `string`.\n at assertType (/usr/src/app/packages/server/node_modules/@sindresorhus/is/dist/index.js:293:15)\n at Object.any (/usr/src/app/packages/server/node_modules/@sindresorhus/is/dist/index.js:386:16)\n at normalizeArguments (/usr/src/app/packages/server/node_modules/got/dist/source/core/index.js:386:21)\n at mergeOptions (/usr/src/app/packages/server/node_modules/got/dist/source/create.js:39:25)\n at Function.got.extend (/usr/src/app/packages/server/node_modules/got/dist/source/create.js:151:22)\n at new REDACTED (/usr/src/app/packages/server/node_modules/_REDACTED_/dist/index.js:31:38)\n at boot (/usr/src/app/packages/server/dist/app.js:180:22)\n at Object.<anonymous> (/usr/src/app/packages/server/dist/app.js:239:9)\n at Module._compile (internal/modules/cjs/loader.js:1085:14)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
  "level": "error",
  "message": "startup error"
}
```
</details>

<details>
<summary>Relevant LOCs</summary>

```js
assert(this.options.token, 'Token required')
assert(this.options.url, 'URL required')
const prefixUrl = new URL(this.options.url)
this.request = got.extend({
  prefixUrl,
  timeout: this.options.timeout || DEFAULT_TIMEOUT,
  headers: {
    Authorization: `Bearer ${this.options.token}`
  }
})
```
</details>

Would hugely appreciate it if `got` was more helpful here.

**Comment by stephenmathieson** [comment]
In my case, a string was being passed as `timeout`. As suggested in the original comment, an error indicating that the `timeout` option was of the incorrect type would be very helpful.

**Comment by movy** [comment]
In my case I was migrating from axios and bad to change `{body: data}` to `{json: data}` in requests.

**Comment by binarymist** [comment]
I also spent a long time debugging an issue (after upgrading to 12.0.1) where by the looks of it `options.json` no longer accepts a json string.

I was getting: `Expected value which is `predicate returns truthy for any value`, received values of types `string``

**Comment by rinogo** [comment]
GAH! Thanks, @movy. That appears to have been my *exact* problem!

I was confused because a quick glance at [the docs for Options](https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#body) make like `body` is a suitable property for making things happen.

**Alas, as you've pointed out, the fix was as simple as using `json` instead of `body`. Perhaps the docs for `body` could be improved to make mention of `json`.**

Of course, arguably the best solution would be to improve the error messages. With that said, here's my error message to help with Google indexing:

```
RequestError: Expected value which is `predicate returns truthy for any value`, received values of types `Object`.
```

**Comment by ryanhssn** [comment]
> In my case, a string was being passed as `timeout`. As suggested in the original comment, an error indicating that the `timeout` option was of the incorrect type would be very helpful.

Thank you, bro 😎

**Comment by guillenotfound** [comment]
Also facing this issue when trying to post FormData object, any hints on how to fix it? I'm using `body` to perform the POST request.

**Comment by movy** [comment]
Coming back here with new project that uses got. This time, `timeout` is expected to be object, not a number, i.e.:
```json
timeout: {
		lookup: 100,
		connect: 50,
		secureConnect: 50,
		socket: 1000,
		send: 10000,
		response: 1000
	}
```

**Comment by Jermont25** [comment]
I want to add that I got the error` Expected value, which is `plain object`, received value of type `number`` when trying to do a get. After a lot of research I found that it was because since version 12 of got, the timeout should be added like this:

```
timeout: {
      request: 5000,
    },
```
Doc: https://github.com/sindresorhus/got/blob/c8902ba3420b2def5aab68b3f889039469d0b1a8/documentation/6-timeout.md

Blog: https://schalkneethling.com/posts/moving-from-got-11-to-12

**Comment by ledlamp** [comment]
I set `options.timeout = {request: 3000};` and got "RequestError: Expected values which are `number` or `undefined`. Received values of type `Function`.". Wtf? There's no function?
