### ISSUE TITLE
Can't use agent in beforeHook

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#1292]
If I put:

```ts
hooks: {
  beforeRequest: [
    opts => {
      const proxies = [];
      const proxy = proxies[Math.floor(Math.random() * proxies.length)];
      opts.agent = new HttpsProxyAgent(proxy) as any;
    }
  ]
}
```

I get:

```
RequestError: The `options.agent` object can contain only `http`, `https` or `http2` properties
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762520)
    at f.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:810576)
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762069)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:746276
onError aJ [RequestError]: The `options.agent` object can contain only `http`, `https` or `http2` properties
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762520)
    at f.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:810576)
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:762069)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:746276 {
  code: undefined,
  timings: undefined
}
```

and if I put:

```ts
hooks: {
  beforeRequest: [
    opts => {
      const proxies = [];
      const proxy = proxies[Math.floor(Math.random() * proxies.length)];
      opts.agent = {
        https: new HttpsProxyAgent(proxy) as any;
      }
    }
  ]
}
```

I get:

```
RequestError: The "options.agent" property must be one of type Agent-like Object, undefined or false. Received object
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826811)
    at new j.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:877067)
    at f.exports (/Users/devchris/Documents/code/nodejs/project/build.js:1:875709)
    at async l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826350)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:810877
onError aJ [RequestError]: The "options.agent" property must be one of type Agent-like Object, undefined or false. Received object
    at l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826811)
    at new j.<computed> (/Users/devchris/Documents/code/nodejs/project/build.js:1:877067)
    at f.exports (/Users/devchris/Documents/code/nodejs/project/build.js:1:875709)
    at async l._makeRequest (/Users/devchris/Documents/code/nodejs/project/build.js:1:826350)
    at async /Users/devchris/Documents/code/nodejs/project/build.js:1:810877 {
  code: 'ERR_INVALID_ARG_TYPE',
  timings: undefined
}
```

Its only happening with the option http2: true, with false, you can pass the agent like that: `opts.agent = new HttpsProxyAgent(proxy) as any;` even if the typing is wrong

And by the way the typing is broken too...

Thanks

**Comment by yovanoc** [comment]
Still doesn't work with http2 and the new 11.2 version for me

**Comment by szmarczak** [comment]
Works for me:

```js
const https = require('https');
const got = require('got');

got('https://github.com', {
    http2: true,
    hooks: {
        beforeRequest: [
            options => {
                const agent = new https.Agent();
                agent._createConnection = agent.createConnection;
                agent.createConnection = (...args) => {
                    console.log('Creating a new HTTPS connection');
                    return agent._createConnection(...args);
                };
                
                options.agent = {
                    https: agent
                };
            }
        ]
    }
}).then(response => console.log(response.statusCode));
```

**Comment by yovanoc** [comment]
wut, I tried with the http2: true, option AND `http2` field too in options.agent not https, it's an error? why this field exists?

**Comment by szmarczak** [comment]
> why this field exists?

Because HTTP/1.1 is not HTTP/2. HTTPS refers to HTTP/1.1 with TLS.

**Comment by yovanoc** [comment]
Yes, but if I put http2: true on a http 2 website, why he doesn't want my options.agent.http2 ??

**Comment by szmarczak** [comment]
I think you're passing a HTTP1 Agent instead of the HTTP2 one. See https://github.com/szmarczak/http2-wrapper/blob/master/README.md#new-http2agentoptions
