### ISSUE TITLE
Password with special characters throws a URI malformed exception

### ISSUE THREAD

**Issue by naphtul** [sindresorhus/got#1317]
#### Describe the bug
 - Node.js version: 12.18.0
 - OS & version: MacOS 10.15.5

My password for the URL has special characters in it. It has the dollar sign ($) and the percent (%). These characters normally need to go through encodeURIComponent().

#### Actual behavior
```
RequestError: URI malformed
    at PromisableRequest._destroy (/node_modules/got/dist/source/core/index.js:1132:21)
    at PromisableRequest.destroy (internal/streams/destroy.js:38:8)
    at /node_modules/got/dist/source/core/index.js:288:26
    at new Request (/node_modules/got/dist/source/core/index.js:291:11)
    at new PromisableRequest (/node_modules/got/dist/source/as-promise/core.js:32:1)
    at makeRequest (/node_modules/got/dist/source/as-promise/index.js:37:29)
    at /node_modules/got/dist/source/as-promise/index.js:196:9
    at /node_modules/p-cancelable/index.js:61:11
    at new Promise (<anonymous>)
    at new PCancelable (/node_modules/p-cancelable/index.js:31:19)
    at decodeURI (<anonymous>)
    at /node_modules/got/dist/source/core/index.js:268:17
    at new Request (/node_modules/got/dist/source/core/index.js:291:11)
    at new PromisableRequest (/node_modules/got/dist/source/as-promise/core.js:32:1)
    at makeRequest (/node_modules/got/dist/source/as-promise/index.js:37:29)
    at /node_modules/got/dist/source/as-promise/index.js:196:9
    at /node_modules/p-cancelable/index.js:61:11
    at new Promise (<anonymous>)
    at new PCancelable (/node_modules/p-cancelable/index.js:31:19)
    at Object.asPromise [as default] (/node_modules/got/dist/source/as-promise/index.js:26:21)
```

#### Expected behavior
A password can have special characters in it, and the library should seamlessly handle it.

#### Code to reproduce
```js
const got = require('got');
const url = 'https://enzmjqa4r8u7.x.pipedream.net';
const options = {
    username: 'test',
    password: 't$es%t',
};
response = got(url, options);
```

#### Checklist
- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by yakov116** [comment]
I think this is the same as #1169

**Comment by szmarczak** [comment]
@sindresorhus I don't think Node.js will fix this anytime soon. What about if we throw when the URL already contains a username / password and encode the `username` & `password` option on our own?

**Comment by sindresorhus** [comment]
Seems like there's some activity: https://github.com/nodejs/node/pull/31450#issuecomment-647719491 I'd prefer to wait.

**Comment by szmarczak** [comment]
@sindresorhus What about now?

**Comment by mctrivia** [comment]
I am having the same problem.  Why can't we encode the uri ourselves using?

`http://${encodeURIComponent(user)}:${encodeURIComponent(pass)}@${host}:${port}/`

**Comment by szmarczak** [comment]
@mctrivia https://github.com/sindresorhus/got/issues/1317#issuecomment-678688287

> if we implement a workaround, Node.js has even less incentive to land the fix.

**Comment by Giotino** [comment]
You can try to polyfill it as follow

```js
const got = require('got')

const authGot = got.extend({
    handlers: [
		(options, next) => {
			if (options.username || options.password) {
                options.headers = {
                    ...options.headers,
                    'Authorization': 'Basic ' + Buffer.from(decodeURIComponent(options.username) + ':' + decodeURIComponent(options.password)).toString('base64')
                };
                
                options.username = '';
                options.password = '';
			}

            return next(options);
	   }
    ],
});

(async () => {
    const response = await got('https://%67uest:guest@jigsaw.w3.org/HTTP/Basic/');
    
    console.log(response.body);
})();
```
