### ISSUE TITLE
`UnhandledPromiseRejectionWarning: GotError: Premature close` when used in puppeteer-page-proxy

### ISSUE THREAD

**Issue by hl5617** [sindresorhus/got#1409]
#### Describe the bug

 - Node.js version: 12.18.0
 - OS & version: CentOS 7.8.2003

#### Actual behavior

Throws an `UnhandledPromiseRejectionWarning` when used with many requests concurrently
```
UnhandledPromiseRejectionWarning: GotError: Premature close
    at onError (/home/hao/fido/js/node_modules/puppeteer-page-proxy/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/hao/fido/js/node_modules/puppeteer-page-proxy/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ClientRequest.onclose (internal/streams/end-of-stream.js:80:15)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/home/hao/fido/js/node_modules/puppeteer-page-proxy/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketCloseListener (_http_client.js:385:9)
    at Socket.emit (events.js:315:20)
    at emitCloseNT (net.js:1655:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

#### Code to reproduce
https://github.com/Cuadrix/puppeteer-page-proxy/blob/master/src/core/proxy.js#L26

**Comment by szmarczak** [comment]
Paste the actual code to reproduce the issue and I'll reopen.
