### ISSUE TITLE
Hostname/IP does not match certificate's altnames: Cert is empty

### ISSUE THREAD

**Issue by octalpixel** [sindresorhus/got#1412]
#### What would you like to discuss?
I have the following issues in term of using a proxy service ("crawlera"). I get the following error 
`RequestError: Hostname/IP does not match certificate's altnames: Cert is empty`. Using tunnel to send httpsOverHttp. The issue only persist when the scraper is moved to AWS.

The full error  goes as follows.
`RequestError: Hostname/IP does not match certificate's altnames: Cert is empty
    at ClientRequest.<anonymous> (/home/ubuntu/project/scrape-test/node_modules/got/dist/source/core/index.js:891:25)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/home/ubuntu/project/scrape-test/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Object.checkServerIdentity (tls.js:279:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1328:27)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) {
  name: 'RequestError',
  code: 'ERR_TLS_CERT_ALTNAME_INVALID',
  timings: {
    start: 1597835558025,
    socket: 1597835558122,
    lookup: 1597835558122,
    connect: 1597835558122,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1597835558209,
    abort: undefined,
    phases: {
      wait: 97,
      dns: 0,
      tcp: 0,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 184
    }
  }
}`
...

If there a possible fix to the problem ? Some can shed some light on this for me ?

#### Checklist

- [ ] I have read the documentation.

**Comment by szmarczak** [comment]
Please file a bug report instead.
