### ISSUE TITLE
RequestError on form-data with boolean

### ISSUE THREAD

**Issue by rubenvereecken** [sindresorhus/got#1472]
#### Describe the bug

 - Node.js version: v12.16.2

I use `form-data` instances for some POST requests so I can attach files. It works beautifully. I recently added a boolean property to the form-data instance which causes a RequestError. It's fine without the boolean.

#### Actual behavior
```
RequestError: Cannot read property 'method' of undefined
    at PromisableRequest.onError (/home/ruben/lessgo/woushe-backend/node_modules/got/dist/source/as-promise/index.js:182:28)
    at Object.onceWrapper (events.js:417:26)
    at PromisableRequest.emit (events.js:322:22)
    at PromisableRequest.EventEmitter.emit (domain.js:482:12)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at validChunk (_stream_writable.js:283:5)
    at PromisableRequest.Writable.write (_stream_writable.js:315:21)
    at FormData.ondata (internal/streams/legacy.js:19:31)
    at FormData.emit (events.js:322:22)
    at FormData.EventEmitter.emit (domain.js:482:12)
    at validChunk (_stream_writable.js:280:10)
    at PromisableRequest.Writable.write (_stream_writable.js:315:21)
    at FormData.ondata (internal/streams/legacy.js:19:31)
    at FormData.emit (events.js:322:22)
    at FormData.EventEmitter.emit (domain.js:482:12)
```

...

#### Code to reproduce

```ts
		const form = new FormData();
                form.append('string', 'okay');
	        form.append('boolean', true); // <-- comment out this line to get rid of the exception
		const res = await this.api.post(`events`, {
			body: form,
			throwHttpErrors: false,
		});
```

#### Checklist

- [x] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by rubenvereecken** [comment]
... Upgrading threw more useful errors.
