### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by zckrs** [sindresorhus/got#1474]
#### Describe the bug

Hi, we use got in many microservice and yesterday we upgrade v11.5.2 to v11.7.0.

Since this upgrade we have some error 
```
RequestError: Cannot read property 'includes' of undefined
    at /src/node_modules/got/dist/source/core/index.js:1246:38
    at Request._beforeError (/src/node_modules/got/dist/source/core/index.js:1273:11)
    at ClientRequest.<anonymous> (/src/node_modules/got/dist/source/core/index.js:959:18)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/src/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at Object.calculateRetryDelay [as default] (/src/node_modules/got/dist/source/core/calculate-retry-delay.js:9:44)
    at /src/node_modules/got/dist/source/core/index.js:1236:71
    at Request._beforeError (/src/node_modules/got/dist/source/core/index.js:1273:11)
    at ClientRequest.<anonymous> (/src/node_modules/got/dist/source/core/index.js:959:18)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/src/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3
```

Do you have any ideas why ? This related to a breaking change ? 

 - Node.js version: 12
 - OS & version: Linux

#### Actual behavior
Throw a strange error independant of our code.

#### Expected behavior
Should work like v11.5.2

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
Can you provide some code to reproduce the issue, thanks.

**Comment by zckrs** [comment]
The bug not occurs each time.
A reproduce code is complicated to provide but something similar is:

```
got(`http://${ip}/${uri}`, {
    method: 'PURGE',
    port: 8080,
    responseType: 'text',
    headers: {
      'X-Forwarded-Proto': 'https',
      Host: domain
    }
  });
```
Used in kubernetes pod to purge cache on varnish. 

I suspect usage of method purge with the recent change on retry feature provided by got.

**Comment by Giotino** [comment]
Are you using `options.retry`? Your error seems to be due to an undefined `options.retry.methods`.

It could be Got that fails to merge the defaults of `options.retry` with your custom ones.

**Comment by zckrs** [comment]
No, we use `got.extend` to add some default option but not on retry.


```
const rfGot = got.extend({
  dnsCache: true,
  headers: {
    'user-agent': `rf-got (${podNamespace} ${hostname})`
  },
  timeout: 10000,
  responseType: 'json',
  handlers: [
    (options, next) => {
      const {context, url}: {context: RfGotContext; url: URL} = options;

      if (!context.token) {
        const xQueryToken = uuidV4();
        options.headers['x-query-token'] = xQueryToken;
        logger.warn(null, xQueryToken, `rf-got generate new X-Query-Token for url ${url.toString()}`);
        return next(options);
      }

      options.headers['x-query-token'] = context.token;

      return next(options);
    }
  ],
  hooks: {
    beforeError: [
      error => {
        const {request} = error;
        if (request) {
          error.message += ` (requestUrl: ${request.requestUrl})`;
        }

        return error;
      }
    ]
  }

});
```

**Comment by prithvijit-dasgupta** [comment]
Hi @zckrs, I can see that `got` restricts the method. How is it that you are calling with `PURGE`? Forgive me if this query is out of context of the issue.

**Comment by zckrs** [comment]
@prithvijit-dasgupta we just used `method` option.


@Giotino I can confirm the bug occur at 11.6.0.

**Comment by szmarczak** [comment]
@prithvijit-dasgupta It's just a TypeScript type. You can still force it to accept non standardized methods.

**Comment by szmarczak** [comment]
@zckrs Are you able to reproduce the bug?

**Comment by zckrs** [comment]
I can reproduce when I upgrade got > v11.6.0

**Comment by szmarczak** [comment]
But are you able to reproduce the bug consistently? Every time? Could you please scratch an example on RunKit or a repo?

**Comment by MarianVasile** [comment]
Here's a public RunKit: https://runkit.com/marianvasile/got-retry-issue

**Comment by MarianVasile** [comment]
nvm, in my case it was (line 12) the `options.retry` that was causing the error.

**Comment by szmarczak** [comment]
@MarianVasile the options aren't renormalized. We should add this to the docs.

**Comment by zckrs** [comment]
My problem seems to fix with v11.8.0. 

Maybe a bug inside one dependence.

**Comment by szmarczak** [comment]
Can't reproduce:

```js
import got from 'got';

try {
    const response = await got('http://httpbingo.org/status/500', { method: 'CUSTOM', responseType: 'text', retry: { limit: 1 } });
    console.log(response.retryCount);
} catch (error) {
    console.log(error.response.retryCount);
}
```
