### ISSUE TITLE
The onCancel handler was attached after the promise settled

### ISSUE THREAD

**Issue by yovanoc** [sindresorhus/got#1489]
#### Describe the bug

 - Node.js version: 14.13
 - OS & version: MacOS Catalina

`The onCancel handler was attached after the promise settled`

#### Actual behavior

This unhandled exception is not catch by a try/catch, but I see that it happen after a timeout error like this issue #1460 

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you please post some code?

**Comment by bkarlson** [comment]
Node.js version: 15.1.0
OS & version:  Windows 10

Just encountered the same, very hard to repro, looks like a race-condition, I will try to dig deeper, but is there any way to catch such exception and just keep running?

**Comment by szmarczak** [comment]
Thanks for the report @bkarlson. Just to confirm - are you running Got 11.8.0?

**Comment by bkarlson** [comment]
Yes, 11.8.0, and the issue seems to be related to `retry` logic, because if I disable it (`retry: 0`) the error never happens. If I have `retry: 3` with other retry options set to default, Got will throw this exception at some point.

**Comment by Giotino** [comment]
An easy fix would be using `if (!thePromise.isCanceled)` before setting the `onCancel` handlers.

I'm still investigating on the root cause.

**Comment by Kikobeats** [comment]
This is still happening.

Here my error trace: https://sentry.io/share/issue/6f578a2a936943cca5afe367e6732995/

**Comment by szmarczak** [comment]
@yovanoc @Kikobeats @bkarlson Can you try again? The `p-cancelable` package has received [a neat fix](https://github.com/sindresorhus/p-cancelable/releases/tag/v2.1.0) that could potentially fix this error. Make sure to update the npm dependencies.

**Comment by Kikobeats** [comment]
@szmarczak I'm still experimenting the error

https://sentry.io/share/issue/c607e343ef6345c38ad391a7c3f43149/

node version is: v14.16.0
got version is: 11.8.2
p-cancelable: 2.1.0

**Comment by szmarczak** [comment]
@Kikobeats Can you show the line where you call `got`? Do you pass any hooks?

**Comment by szmarczak** [comment]
@Kikobeats can you replace `dist/as-promise/index.js` with https://gist.github.com/szmarczak/310ee80c1085bdacd042c64fd992ef76 ? I made some [changes](https://www.diffchecker.com/oFkLndSD) so it [logs](https://gist.github.com/szmarczak/310ee80c1085bdacd042c64fd992ef76#file-index-js-L47) what happened.

**Comment by szmarczak** [comment]
@bkarlson @yovanoc Can you too try the above?

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/4cce4de19ed577f481ba45a023b395a29cadce86/source/as-promise/index.ts#L33 should reuse the previous request options on retry because `promise.json()` modifies the options

**Comment by Kikobeats** [comment]
@szmarczak In my case is hard to say since there are a couple of dependencies using `got` and the stack trace is not revealing the details about which the origin of the problem.

Also, since this is running a production environment, I can't replace it in an easy way.

Maybe can you release a `got` RC version so I can force to be used?

**Comment by szmarczak** [comment]
I have an idea how to reproduce this. `request.destroy()` may be called, the promise may be canceled, but `request` hasn't been emitted yet and there is no check if it has been destroyed. Will check this.

**Comment by szmarczak** [comment]
Actually no because it's destroyed here https://github.com/sindresorhus/got/blob/4cce4de19ed577f481ba45a023b395a29cadce86/source/core/index.ts#L1469-L1472

**Comment by szmarczak** [comment]
I think I finally may be able to reproduce this.

**Comment by szmarczak** [comment]
@Kikobeats What is the timeout event? Is it `request` event?

**Comment by szmarczak** [comment]
Also can you do `npm ls got` and show me which versions are being used?

**Comment by szmarczak** [comment]
@Kikobeats @bkarlson @yovanoc If your project uses Got directly you can try

```js
const isResponseOk = response => {
	const {statusCode} = response;
	const limitStatusCode = response.request.options.followRedirect ? 299 : 399;

	return (statusCode >= 200 && statusCode <= limitStatusCode) || statusCode === 304;
};

const instance = got.extend({
    hooks: {
        afterResponse: [
            response => {
                if (isResponseOk(response)) {
                    response.request.destroy();
                }
            
                return response;
            }
        ]
    }
});
```

If so, please let me know if that fixes the issue.

**Comment by Kikobeats** [comment]
Hey @szmarczak, I'm running your code snippet on my production servers since yesterday and I didn't experiment errors until now (maybe it needs a bit of extra time)

**Comment by CvBlixen** [comment]
> If so, please let me know if that fixes the issue.

That one fixed the issue for me as well. Thank you very much @szmarczak ! 🙏🏻 

I am running got as part of generating a fake environment with lots of pictures. I have a feeling many uploads in quick succession are causing this.

**Comment by szmarczak** [comment]
@CvBlixen Yes! If you have set the `response` timeout and the request payload has been fully written after the `response` event has been emitted, this bug can occur. It can also happen with a `read` timeout.

**Comment by szmarczak** [comment]
The issue can also occur when a `send ` timeout is set and the connection fails. `socket.writable` check is missing in https://github.com/sindresorhus/got/blob/4cce4de19ed577f481ba45a023b395a29cadce86/source/core/utils/timed-out.ts#L157

**Comment by szmarczak** [comment]
Also the `secureConnect` timeout should not run if `rejectUnauthorized` is set to `false`.

**Comment by szmarczak** [comment]
I wonder if this check https://github.com/sindresorhus/got/blob/4cce4de19ed577f481ba45a023b395a29cadce86/source/core/utils/timed-out.ts#L135 can be replaced with `socket.connecting`.

**Comment by szmarczak** [comment]
`request` timeout can also cause this. For example when the error is emitted on `response` instead.

**Comment by szmarczak** [comment]
@CvBlixen @bkarlson Before you applied the fix, were you getting `TimeoutError`s as well? If so, can you share the stack trace along with the message please?

**Comment by tsightler** [comment]
I'm not sure if this will help, but I think I'm seeing this.  I've been attempting to troubleshoot why a network interruption causes my code (which uses ring-client-api which uses got) stops updating even after the network connection is reestablished, but only when using http2.  I modified ring-client-api to set the timeout to 10 seconds, and then I interrupt the network connection to create the timeout but I get this which I can't seem to trap:

```
(node:69900) UnhandledPromiseRejectionWarning: Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/opt/ring-mqtt/node_modules/ring-client-api/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/opt/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/opt/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (events.js:422:26)
    at Request.emit (events.js:315:20)
    at Timeout.retry (/opt/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/core/index.js:1264:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:69900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:69900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:292
      throw er; // Unhandled 'error' event
      ^

TimeoutError: Timeout awaiting 'request' for 10000ms
    at Timeout.timeoutHandler [as _onTimeout] (/opt/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7)
Emitted 'error' event on Request instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at errorOrDestroy (internal/streams/destroy.js:168:7)
    at internal/streams/writable.js:613:7
    at /opt/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/core/index.js:1348:17
    at ClientRequest.onerror (internal/streams/writable.js:680:5)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/opt/ring-mqtt/node_modules/ring-client-api/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  event: 'request',
  code: 'ETIMEDOUT'
}

```

Any help would be appreciated.

**Comment by szmarczak** [comment]
@tsightler So... are you able to reproduce this?

**Comment by tsightler** [comment]
Yes, 100% reproducible if I have an active HTTP2 session with a configured timeout and then block the internet connection to simulate a communication failure.  This produces a request timeout as shown above.  I can somewhat overcome the issue if I set retry: 0, as this seems to suppress the error, although then I get a different error from http2-wrapper, although that one doesn't crash the process so I'm thinking I may be able to work around it.

I'm admittedly super new to all of this as normally the underlying interactions with HTTP are below the code I maintain.  The API I use recently switched to using HTTP2 by default for the connection to the servers, and this has introduced the issue of failure to reconnect.  I did notice that you say that HTTP2 is only supported for Node 15, so that's interesting, although I did try Node 15, but the timeout error above persisted.

**Comment by Allain55** [comment]
Got this bug today after migrating to esm. Not sure if it's related but this code's worked for months

**Comment by szmarczak** [comment]
@Allain55 https://github.com/sindresorhus/got/issues/1489#issuecomment-805485731 let me know if this fixes it

**Comment by Allain55** [comment]
@szmarczak this fix doesn't help, I still get this error when I break up my internet connection

**Comment by szmarczak** [comment]
@Allain55 Can you describe exactly the steps to reproduce the issue? If you could include the code that would be awesome.

**Comment by Allain55** [comment]
Sure, I have this method (with improved error handling but that's irrelevant):

```
const getStatusCode = async (url) => {
	try {
		const response = await got.get(
			url,
			{
				'followRedirect': false,
				'http2'         : true,
				'timeout'       : 5_000,
				'headers'       : {
					'cookie': 'example=true; SameSite=Strict'
				}
			}
		);

		return response.statusCode;
	} catch (err) {
		console.error(err.code)
		
		return null;
	}
};
```

Thanks for checking it!

**Comment by simontabor** [comment]
Just experienced this issue.

We're running the workaround for https://github.com/sindresorhus/got/issues/1385, wondering if it could be related?

**Comment by omardoma** [comment]
We are also facing that issue with v11.8.2, happens with long running scraping jobs after a while,  are there any confirmd workarounds available?

**Comment by szmarczak** [comment]
Yes, upgrade to v12 beta.

**Comment by mooyoul** [comment]
Hello @szmarczak, I'm not sure that fixes in v12 beta handles this case, but I just want to share my case to help:

1. Configured Got instance with retry & timeout options, and `request` function option which calls `http2Wrapper.request` internally with customized HTTP2 Agent to handle connection timeout.
2. Make a request using (1)
3. TLS Socket of (2) is timed out, Agent never created session, so our custom http2Wrapper Agent destroys TLS Socket by calling `tlsSocket.destroy(new Error("TLSSocket Timeout"))`
4. Then this happens.

**Comment by dimitrov-adrian** [comment]
I am also facing this problem because of the metascrape package.

If I comment out `onCancel.shouldReject = false;` in https://github.com/sindresorhus/got/blob/v11/source/as-promise/index.ts#L39 the issue does not appears. Not sure about the root of the issue, but may be the onCancel is lost somewhere.

**Comment by kirillgroshkov** [comment]
Yes, we're having this issue too.

Ended up creating a `patch` (via `patch-package`) on `p-cancelable` to avoid this error becoming an unhandledRejection and killing everything (in our production Backend and CI pipelines).

Here's the patch we're using:

```patch
diff --git a/node_modules/p-cancelable/index.js b/node_modules/p-cancelable/index.js
index 186adce..f8637cc 100644
--- a/node_modules/p-cancelable/index.js
+++ b/node_modules/p-cancelable/index.js
@@ -45,7 +45,9 @@ class PCancelable {
 
 			const onCancel = handler => {
 				if (!this._isPending) {
-					throw new Error('The `onCancel` handler was attached after the promise settled.');
+          // Kirill: suppressing this error now, as it caused UnhandledRejection or even UncaughtException and killed node.js process
+					// throw new Error('The `onCancel` handler was attached after the promise settled.');
+          return console.warn('[patched to not throw] The `onCancel` handler was attached after the promise settled.')
 				}
 
 				this._cancelHandlers.push(handler);

```

**Comment by Kikobeats** [comment]
@kirillgroshkov thanks for sharing, I'm going to test that solution for a while and write here soon.

Unfortunately, the [workaround](https://github.com/sindresorhus/got/issues/1489#issuecomment-805485731) proposed by @szmarczak is not working anymore to me.

Nothing changed in a remarkable way on my setup, I'm still using got@11.8.3 under node v16.131

**Comment by kejiweixun** [comment]
Having the same issue, any progress?

**Comment by Keller18306** [comment]
```
Error: Cannot call end after a stream was destroyed
    at new NodeError (node:internal/errors:370:5)
    at errorBuffer (node:internal/streams/writable:522:26)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_STREAM_DESTROYED'
}

D:\VSCode\AutoContest Lolz\node_modules\p-cancelable\index.js:48
throw new Error('The `onCancel` handler was attached after the promise settled.');
           ^
Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (D:\VSCode\AutoContest Lolz\node_modules\p-cancelable\index.js:48:12)
    at makeRequest (D:\VSCode\AutoContest Lolz\node_modules\got\dist\source\as-promise\index.js:38:13)
    at Request.<anonymous> (D:\VSCode\AutoContest Lolz\node_modules\got\dist\source\as-promise\index.js:143:17)
    at Object.onceWrapper (node:events:514:26)
    at Request.emit (node:events:394:28)
    at Request.emit (node:domain:470:12)
    at Timeout.retry (D:\VSCode\AutoContest Lolz\node_modules\got\dist\source\core\index.js:1270:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

![image](https://user-images.githubusercontent.com/23178771/160731507-902225ce-00f9-4999-8f03-efa28e04c6f4.png)

**Comment by BouweCeunen** [comment]
Just an FYI I also got the same issue very suddenly, reading through this thread to see what I can do.

**Comment by LucCADORET** [comment]
I am having this issue a lot with the version v11.8.5, and node 16. I am trying to upgrade to 12.1.0, but since it's pure esm, it's honestly very tedious to perform the migration of a whole project for this one bug.

**Comment by yacineblr** [comment]
Any news about this ?

**Comment by szmarczak** [comment]
The bug is not fixed in Got v12 either, I haven't got the time to inspect it in much detail yet

**Comment by shlomo-artlist** [comment]
I also recently started to see this error often in our services. We use got with shared custom extensions in all of our micro services, and it worked just fine, until we upgraded from Node 14 to Node 16.
We also can't just upgrade all of our services and modules to ESM.
If this cannot be fixed for CommonJS versions, please let us know.
If that's the case, I'm afraid we might need to switch to another library.

**Comment by jthomerson** [comment]
I have the same situation @lukelafountaine describes. It's unclear to me from the tagging of this issue if any of the core developers are going to work on this? Or if you're needing a community contribution?

**Comment by nduthoit** [comment]
Like @shlomo-artlist we've started seeing this error after upgrading from Node 12 to Node 16 (got v11.8.5) in requests with retries. 

```json
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: The `onCancel` handler was attached after the promise settled.",
    "reason": {
        "errorType": "Error",
        "errorMessage": "The `onCancel` handler was attached after the promise settled.",
        "stack": [
        "Error: The `onCancel` handler was attached after the promise settled.",
        "    at onCancel (/var/task/node_modules/p-cancelable/index.js:48:12)",
        "    at makeRequest (/var/task/node_modules/got/dist/source/as-promise/index.js:38:13)",
        "    at Request.<anonymous> (/var/task/node_modules/got/dist/source/as-promise/index.js:143:17)",
        "    at Object.onceWrapper (node:events:642:26)",
        "    at Request.emit (node:events:527:28)",
        "    at Request.emit (node:domain:475:12)",
        "    at Timeout.retry (/var/task/node_modules/got/dist/source/core/index.js:1278:30)",
        "    at listOnTimeout (node:internal/timers:559:17)",
        "    at processTimers (node:internal/timers:502:7)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: The `onCancel` handler was attached after the promise settled.",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)",
        "    at process.emit (node:events:527:28)",
        "    at process.emit (node:domain:475:12)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)",
        "    at emit (node:internal/process/promises:140:20)",
        "    at processPromiseRejections (node:internal/process/promises:274:27)",
        "    at processTicksAndRejections (node:internal/process/task_queues:97:32)"
    ]
}
```

@szmarczak could it be related to the change to use `autoDestroy: true` in incoming message introduced in Node 16 [#33035](https://github.com/nodejs/node/pull/33035/files)?

I've been working on creating a test case to reproduce it. I'll report back if I'm successful.

**Comment by szmarczak** [comment]
No, it has to do with the retry mechanism. If you disable retries then the issue is gone.

**Comment by petertflem** [comment]
We had this issue after upgrading from `11.8.3` to `11.8.5`. Downgraded back to `11.8.3` fixed the issue. Don't know if we are using retries.

**Comment by michael42** [comment]
> No, it has to do with the retry mechanism. If you disable retries then the issue is gone.

Unfortunately, we still hit the issue even with `got({ retry: 0 })` and a hand-written for-loop for retries (using got 11.8.5).

**Comment by nduthoit** [comment]
@szmarczak after doing some troubleshooting we figured out that in our case the error is caused by an `ECONNRESET` error being triggered on the request after a successful response has been received and processed. The `ECONNRESET` triggers got's retry mechanism but by then the promise has already resolved by the successful response.

A colleague was able to create a reproducible test case. It triggers the error with got v11.8.5 but not with got v12.5.0 (using node 16.15.0 in both cases). It does that by resetting the TCP connection on the server side shortly after sending the response. The code and sample output is available on [this gist](https://gist.github.com/nduthoit/00b0623a6b4a9a61f1e264ea1f982d33).

**Comment by spacecakes** [comment]
> @szmarczak after doing some troubleshooting we figured out that in our case the error is caused by an `ECONNRESET` error being triggered on the request after a successful response has been received and processed. The `ECONNRESET` triggers got's retry mechanism but by then the promise has already resolved by the successful response.

I discovered this too recently. At least in our case it seems to be a race condition only happening on fast connections. As weird as it sounds, a workaround is to connect to a slower Internet connection (in my case through my phone). This has completely solved my team's issues with this error that we saw when downloading Chromium. 

Your mileage may vary depending on where you see this error, but hopefully this might help someone.

**Comment by nduthoit** [comment]
@spacecakes wow, I wouldn't have expected that as a workaround... 

I'm assuming you don't have control of `got` in this case? If you do (but can't upgrade to v12+) you could do the following to abort the retry when it's triggered by an `ECONNRESET` after a successful response:

```javascript
const isResponseOk = (response) => {
    const { statusCode } = response,
          limitStatusCode = response.request.options.followRedirect ? 299 : 399;

    return response.complete && ((statusCode >= 200 && statusCode <= limitStatusCode) || statusCode === 304);
};

const instance = got.extend({
    retry: {
        calculateDelay: (retryObject) => {
            const error = retryObject.error,
                  response = error.response;

            // Abort the retry (by returning a delay of 0) if we have an ECONNRESET
            // error after a successful response.
            if (error.code === 'ECONNRESET' && response && isResponseOk(response)) {
                try {
                    console.info(JSON.stringify({
                        evt: 'got-abort-late-econnreset-retry',
                        error: error,
                        response: {
                            statusCode: response.statusCode,
                            statusMessage: response.statusMessage,
                            complete: response.complete,
                        },
                    }));
                } catch(err) {
                    console.error(err);
                }

                return 0;
            }

            return retryObject.computedValue;
        },
    }
});
```

**Comment by spacecakes** [comment]
> @spacecakes wow, I wouldn't have expected that as a workaround... 
> 

You can imagine it took some time and trial and error to figure this out. 😅

We don't have control no. It's a peer dependency in our test suite that downloads Chromium, which in turn uses `got`. Me and Swedish college were the only ones in our team experiencing it, and the only ones on fast fiber connections.  

It doesn't make any sense to me either, but we've been able to repeat it; if fails consistently on 250MB+ connections and works consistently on lesser ones. Fortunately once installed we don't have to run it again for a long time.

**Comment by EdgarHarutyunyan02** [comment]
I am having this issue with got v11.8.6 and Node 20 when I have http2 enabled. With http1.1 I don't see the issues.

Snippet of my code below.

```js
got.get(`https://www.google.com`,
  {
    timeout: { request: 100 }, // Made the timeout small so it's retried.
    http2: true,
    dnsCache: true,
    retry: 3,
  },
)
```
