### ISSUE TITLE
The "lookup timeout no error (ip address)" test is fail on node@12.19.0

### ISSUE THREAD

**Issue by mrmlnc** [sindresorhus/got#1497]
#### Describe the bug

 - Node.js version: `12.19.0`
 - OS & version: `Ubuntu 20.04 LTS`

#### Steps to reproduce

```bash
git clone https://github.com/sindresorhus/got
cd got

nvm use 12.19.0
# or
volta install node@12.19.0
# or
nvs 12.19.0

npm i
npm t
```

#### Description

The problem was found in https://github.com/sindresorhus/got/pull/1495#issuecomment-706341339.

<details>

<summary>The original output from `npm t`</summary>

```js
  lookup timeout no error (ip address)

  Promise rejected with:

  RequestError {
    code: 'ECONNRESET',
    timings: {
      abort: undefined,
      connect: 0,
      end: undefined,
      error: 800,
      lookup: 0,
      phases: {
        dns: 0,
        download: undefined,
        firstByte: undefined,
        request: 0,
        tcp: 0,
        tls: undefined,
        total: 800,
        wait: 0,
      },
      response: undefined,
      secureConnect: undefined,
      socket: 0,
      start: 0,
      upload: 0,
    },
    message: 'socket hang up',
  }

  › dist/test/timeout.js:271:13
  › dist/test/helpers/with-server.js:37:15



  Uncaught exception in test/timeout.ts

  Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
  Please open an issue with this stack trace at https://github.com/nodejs/node/issues


  › Please open an issue with this stack trace at https://github.com/nodejs/node/issues
  › assert (internal/assert.js:14:11)
  › TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  ─

  1 test failed
```

</details>

#### Additional debug

After some debug I found the following error:

<details>

<summary>Request error</summary>

```js
RequestError: socket hang up
    at ClientRequest.<anonymous> (/home/mrmlnc/projects/got/dist/source/core/index.js:957:25)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/home/mrmlnc/projects/got/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketOnEnd (_http_client.js:459:9)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  timings: {
    start: 0,
    socket: 0,
    lookup: 0,
    connect: 0,
    secureConnect: undefined,
    upload: 0,
    response: undefined,
    end: undefined,
    error: 800,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 0,
      tls: undefined,
      request: 0,
      firstByte: undefined,
      download: undefined,
      total: 800
    }
  }
}
```

</details>

Also I found that the test is successful when run only it (by `.only`). And the test always fail if it is run after the [`connect timeout`](https://github.com/sindresorhus/got/blob/390b1451423df610686894194612647abca98dea/test/timeout.ts#L226) test.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Got 12 (releasing in the next few days) doesn't support Node.js 12, closing.
