### ISSUE TITLE
specific url will have error: RequestError: URI malformed

### ISSUE THREAD

**Issue by JMVoid** [sindresorhus/got#1583]
#### Describe the bug

 - Node.js version: v14.15.1
 - OS & version:  macOS Mojave version 10.14.6

#### Actual behavior
RequestError: URI malformed
    at Request._destroy (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/core/index.js:1369:21)
    at Request.destroy (internal/streams/destroy.js:39:8)
    at /Users/jmvoid/electron/x2gui/node_modules/got/dist/source/core/index.js:348:26
    at new Request (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/core/index.js:351:11)
    at makeRequest (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/as-promise/index.js:35:29)
    at /Users/jmvoid/electron/x2gui/node_modules/got/dist/source/as-promise/index.js:147:9
    at /Users/jmvoid/electron/x2gui/node_modules/p-cancelable/index.js:61:11
    at new Promise (<anonymous>)
    at new PCancelable (/Users/jmvoid/electron/x2gui/node_modules/p-cancelable/index.js:31:19)
    at Object.asPromise [as default] (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/as-promise/index.js:33:21)
    at decodeURI (<anonymous>)
    at /Users/jmvoid/electron/x2gui/node_modules/got/dist/source/core/index.js:326:17
    at new Request (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/core/index.js:351:11)
    at makeRequest (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/as-promise/index.js:35:29)
    at /Users/jmvoid/electron/x2gui/node_modules/got/dist/source/as-promise/index.js:147:9
    at /Users/jmvoid/electron/x2gui/node_modules/p-cancelable/index.js:61:11
    at new Promise (<anonymous>)
    at new PCancelable (/Users/jmvoid/electron/x2gui/node_modules/p-cancelable/index.js:31:19)
    at Object.asPromise [as default] (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/as-promise/index.js:33:21)
    at getPromiseOrStream (/Users/jmvoid/electron/x2gui/node_modules/got/dist/source/create.js:43:121) {
  code: undefined,
  timings: undefined
}

#### Expected behavior

no error, and get response successfully

#### Code to reproduce

(async () => {
  try {
    const response = await got(
      'https://subcon.dlj.tf/sub?target=clash&new_name=true&url=vmess%3A%2F%https://subcon.py6.pw/sub?target=clash&new_name=true&url=vmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogImhrLmFsaWNsb3VkMDEiLA0KICAiYWRkIjogImhrLmFsaWNsb3VkMDEuYml0c3R1bm5lbC54eXoiLA0KICAicG9ydCI6ICI0NDMiLA0KICAiaWQiOiAiNDc3Yzg1YWYtZTFkNi00ZjU1LTg3NTgtYzhiMzkxZGMxZjJlIiwNCiAgImFpZCI6ICIxNiIsDQogICJuZXQiOiAidGNwIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAidGxzIg0KfQ%3D%3D&insert=false%3D%3D&insert=false'
    );
    console.log(response);
  } catch (error) {
    console.log(error);
  }
})();

#### Checklist

- [ x] I have read the documentation.
- [ x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
The error is valid

**Comment by Giotino** [comment]
Your URL is missing the protocol (e.g. `https://`) and, BTW, it seems that you've copied the first part 2 times.
