### ISSUE TITLE
RequestError: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by me-nkr** [sindresorhus/got#1685]
#### What would you like to discuss?

 - Node.js version:  v14.16.1
 - OS & version:  Ubuntu 20.4 

#### Full Error Report :

RequestError: Parse Error: Invalid header value char
    at ClientRequest.<anonymous> (/home/ubuntu/Projects/ProjectFolder/SubFolder/AppFolder/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/home/ubuntu/Projects/ProjectFolder/SubFolder/AppFolder/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketOnData (_http_client.js:516:9)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'HPE_INVALID_HEADER_TOKEN',
  timings: {
    start: 1618248030829,
    socket: 1618248030836,
    lookup: 1618248030968,
    connect: 1618248031057,
    secureConnect: 1618248031197,
    upload: 1618248031198,
    response: undefined,
    end: undefined,
    error: 1618248031999,
    abort: undefined,
    phases: {
      wait: 7,
      dns: 132,
      tcp: 89,
      tls: 140,
      request: 1,
      firstByte: undefined,
      download: undefined,
      total: 1170
    }
  }
}

it is expected to return the response from the requested url, **It was working before and all of a sudden it's not.**

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
Please fill out the entire issue template.

**Comment by szmarczak** [comment]
The error is correctly thrown by the parser. The server returned a header with an invalid value.
