### ISSUE TITLE
RequestError: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by ram-livwell** [sindresorhus/got#1776]
I'm processing some requests but suddenly I got this error

 ```
Error while loading plugins :
 RequestError: connect ECONNREFUSED 127.0.0.1:443
     at ClientRequest.<anonymous> (/usr/share/nginx/html/sample_node/node_modules/got/dist/source/core/index.js:956:111)
     at Object.onceWrapper (events.js:482:26)
     at ClientRequest.emit (events.js:387:35)
     at ClientRequest.origin.emit (/usr/share/nginx/html/sample_node/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
     at TLSSocket.socketErrorListener (_http_client.js:475:9)
     at TLSSocket.emit (events.js:375:28)
     at emitErrorNT (internal/streams/destroy.js:106:8)
     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
     at processTicksAndRejections (internal/process/task_queues.js:82:21)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
   code: 'ECONNREFUSED',
   timings: {
     start: 1625623249931,
     socket: 1625623249933,
     lookup: 1625623249935,
     connect: undefined,
     secureConnect: undefined,
     upload: undefined,
     response: undefined,
     end: undefined,
     error: 1625623249939,
     abort: undefined,
     phases: {
       wait: 2,
       dns: 2,
       tcp: undefined,
       tls: undefined,
       request: undefined,
       firstByte: undefined,
       download: undefined,
       total: 8
     }
   }
 }
```

**Comment by szmarczak** [comment]
It means the connection was refused.

**Comment by ram-livwell** [comment]
can you tell me what might be the reason ?

**Comment by szmarczak** [comment]
If you're not querying localhost then probably you're using an old version of `agent-base`.

If you're querying localhost, then the server probably closed.
