### ISSUE TITLE
I am Getting this when I Run with Electron.

### ISSUE THREAD

**Issue by kingbotss** [sindresorhus/got#1875]
TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'.
    at Object.<anonymous> (D:\electron\simple\node_modules\got\node_modules\cacheable-lookup\source\index.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.require.extensions.(anonymous function) [as .js] (D:\electron\simple\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\electron\simple\node_modules\got\dist\source\core\index.js:12:28)
    at Object.<anonymous> (D:\electron\simple\node_modules\got\dist\source\core\index.js:1493:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.require.extensions.(anonymous function) [as .js] (D:\electron\simple\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

PS: It is working without electron. If I start calling process from Electron this error arrive.

**Comment by sindresorhus** [comment]
Got supports Node.js. While Got should work fine in the **latest** Electron version, we cannot provide support for it. However, if something is reproducible in plain Node.js, we're happy to take a look.

Also, the latest Got beta will not work in Electron as Electron doesn't yet support ESM.

**Comment by kingbotss** [comment]
![image](https://user-images.githubusercontent.com/80538787/134549762-d5ce82c7-0f87-4758-b00c-ba4ba84f2ff2.png)

**Comment by kingbotss** [comment]
@sindresorhus  

I Don't think so. If I remove cachable-lookup module it takes too much time (waiting long time).
But no error message shows. 
I think it is something with that module.

**Comment by kingbotss** [comment]
Updating to latest versions both GOT & Electron seems to be working.
