### ISSUE TITLE
12.0.1 regression: interaction with ts-node and nyc raises TypeError 

### ISSUE THREAD

**Issue by ClementValot** [sindresorhus/got#1962]
#### Describe the bug

 - Node.js version: v16.3.1
 - OS & version: Windows 10 

Bumping `got` from `11.8.3` to `12.0.1` made `ts-node` and `nyc`-based  script raise TypeError

#### Actual behavior

`npm test` raises the following stack: 

> TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for D:\Path\To\My\File\myFile.test.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (D:\Projects\WebstormProjects\testing-tools\node_modules\mocha\lib\nodejs\esm-utils.js:7:14)
    at async Object.exports.requireOrImport (D:\Projects\WebstormProjects\testing-tools\node_modules\mocha\lib\nodejs\esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (D:\Projects\WebstormProjects\testing-tools\node_modules\mocha\lib\nodejs\esm-utils.js:88:20)
    at async singleRun (D:\Projects\WebstormProjects\testing-tools\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (D:\Projects\WebstormProjects\testing-tools\node_modules\mocha\lib\cli\run.js:374:5)

#### Expected behavior

`npm test` raises no Error

#### Code to reproduce

package.json
```json
  "scripts": {
    "test": "nyc mocha -r ts-node/register 'test/**/*.test.ts'"
  },
  "dependencies": {
    "got": "^12.0.1"
  }, 
  "devDependencies": {
    "mocha": "^9.1.3",
    "nyc": "^15.1.0",
    "ts-node": "^10.4.0"
  }
```

tsconfig.json
```json
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,
    "experimentalDecorators": true,
    "outDir": "./lib",
    "allowJs": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "declaration": true,
    "declarationDir": "./types",
    "declarationMap": true
  },
  "ts-node": {
    "transpileOnly": true
  }
}
```

#### Debugging ideas 
Googling on what raises this exception with `ts-node` leads me to think this has to do with the following change in package.json: 

`11.8.3 package.json`
```json
"nyc": {
		"extension": [
			".ts"
		],
		"exclude": [
			"**/test/**"
		]
	}
```

`12.0.1 package.json`
```json
"nyc": {
		"reporter": [
			"text",
			"html",
			"lcov"
		],
		"extension": [
			".ts"
		],
		"exclude": [
			"**/test/**"
		]
	}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Please read the release notes thoroughly: https://github.com/sindresorhus/got/releases/tag/v12.0.0
