### ISSUE TITLE
Handle error in got.stream

### ISSUE THREAD

**Issue by DimitryDushkin** [sindresorhus/got#202]
So:

```js
got.stream('https://example.com/forbidden.jpg').on('error', (err) => { console.log(err); });
```

App always crashes with 
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
HTTPError: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (/Users/dndushkin/ydf/img-moderate/node_modules/got/index.js:173:24)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at Immediate._onImmediate (/Users/dndushkin/ydf/img-moderate/node_modules/got/index.js:54:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Using `try-catch` not working. How to handle this error?

**Comment by floatdrop** [comment]
@DimitryDushkin we have [test](https://github.com/sindresorhus/got/blob/master/test/stream.js#L90-L101) on this case, can you post a code, that reproduces this problem?
