### ISSUE TITLE
Getting authentication error on Node v17 and Got v12.0.4

### ISSUE THREAD

**Issue by SudhirRamaniOD** [sindresorhus/got#2035]
I am trying to use post request with Got v12.0.4 and Node v17 and getting below error. However same token and code is working with Got v11.8.3

HTTPError: Response code 401 (Authorization Required)
at Request.<anonymous> (file:///app/node_modules/got/dist/source/as-promise/index.js:86:42)
at Object.onceWrapper (node:events:642:26)
at Request.emit (node:events:539:35)
at Request.emit (node:domain:475:12)
at Request._onResponseBase (file:///app/node_modules/got/dist/source/core/index.js:691:22)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Request._onResponse (file:///app/node_modules/got/dist/source/core/index.js:730:13)

#### Checklist

- [x] I have read the documentation.

**Comment by pavannarayan05** [comment]
I am also getting the same error. Any suggestions on this?

**Comment by SudhirRamaniOD** [comment]
Not required. It is working as per expectation.
