### ISSUE TITLE
How to retry socket hang up

### ISSUE THREAD

**Issue by nicoandmee** [sindresorhus/got#2040]
#### What would you like to discuss?
Occasionally I run into errors like this:
```
RequestError: socket hang up
    at ClientRequest.<anonymous> (/home/browser/node_modules/got-cjs/dist/source/core/index.js:820:126)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (/home/browser/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketOnEnd (node:_http_client:478:9)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at connResetException (node:internal/errors:692:14)
    at TLSSocket.socketOnEnd (node:_http_client:478:23)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21
```
In this case, my thinking is maybe changing HTTP agent would help. In the `afterResponse` hook, there is the `retryWithMergedOptions` which would support this use-case. But AFAIK this hook won't be called in the event of a `socket hang up`. Is there any way to do it?
Thanks!
...

#### Checklist

- [ ✔️ ] I have read the documentation.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md#limit
