### ISSUE TITLE
got.get hangs when calling TikTok

### ISSUE THREAD

**Issue by gouku** [sindresorhus/got#2070]
#### Describe the bug

 - Node.js version: v16.15.1
 - OS & version: macOS 12.4

#### Actual behavior

The request seems hang forever for `got` when requesting TikTok. But it works for `node-fetch`.

#### Expected behavior

Get correct respond

#### Code to reproduce

```js
import got from 'got';
import fetch from 'node-fetch';

// Will hang forever
const gotResp = await got.get("https://www.tiktok.com/@shylilytwitch");
console.log(gotResp.body);

// This works
const fetchResp = await fetch('https://www.tiktok.com/@shylilytwitch');
console.log(await fetchResp.text());
```

You have to set timeout for `got` to get errors:

```js
const gotResp = await got.get("https://www.tiktok.com/@shylilytwitch", {
  timeout: {
    request: 2000
  },
});
```

Output:

```js
╰─>$ node test.js
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (file:///Users/git/project/node_modules/got/dist/source/core/index.js:760:61)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (file:///Users/git/project/node_modules/got/dist/source/core/timed-out.js:42:25)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  input: undefined,
  code: 'ETIMEDOUT',
  timings: {
    start: 1656886389774,
    socket: 1656886389774,
    lookup: 1656886389778,
    connect: 1656886389779,
    secureConnect: 1656886389971,
    upload: 1656886389971,
    response: undefined,
    end: undefined,
    error: 1656886391777,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 4,
      tcp: 1,
      tls: 192,
      request: 0,
      firstByte: undefined,
      download: undefined,
      total: 2003
    }
  },
  name: 'TimeoutError',
  options: Options {
    _unixOptions: undefined,
    _internals: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: 2000,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: undefined,
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'GET',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: <ref *1> URL {
        [Symbol(context)]: URLContext {
          flags: 400,
          scheme: 'https:',
          username: '',
          password: '',
          host: 'www.tiktok.com',
          port: null,
          path: [ '@shylilytwitch' ],
          query: null,
          fragment: null
        },
        [Symbol(query)]: URLSearchParams {
          [Symbol(query)]: [],
          [Symbol(context)]: [Circular *1]
        }
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined
    },
    _merging: false,
    _init: [ { timeout: { request: 2000 }, method: 'get' } ]
  },
  event: 'request'
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Try turning of retrying, like I also suggested here: https://github.com/sindresorhus/got/issues/2071#issuecomment-1175465315

**Comment by gouku** [comment]
> Try turning of retrying

It works. but weird. This is an expected behavior or bug?

**Comment by szmarczak** [comment]
Not a bug, see https://github.com/sindresorhus/got/issues/2071#issuecomment-1186363368

> You have to set timeout for got to get errors:

It's always good practice to set timeouts :)
