### ISSUE TITLE
Options freezing breaks abort signal

### ISSUE THREAD

**Issue by svvac** [sindresorhus/got#2099]
The `Options` objects [freeze the abort signal][1] if it gets passed. As a result setting the `signal` prop ends up breaking the signal under node as the builtin code sets private properties when calling `AbortController.abort()`.

This makes it impossible to pass a default abort signal to a `Got` instance as the runtime will throw when aborting.

- NodeJS `v16.15.1`
- Got `v12.3.0`

[1]: https://github.com/sindresorhus/got/blob/e032b60ff3285403b8f9627dcdd32aae39867d7a/source/core/options.ts#L2524

```javascript
import got from 'got';
const abortCtrl = new AbortController();
const got2 = got.extend({
    signal: abortCtrl.signal,
});
abortCtrl.abort();
```

```console
$ node test.mjs
node:internal/abort_controller:279
  signal[kAborted] = true;
                   ^

TypeError: Cannot assign to read only property 'Symbol(kAborted)' of object '#<AbortSignal>'
    at abortSignal (node:internal/abort_controller:279:20)
    at AbortController.abort (node:internal/abort_controller:315:5)
    at file:///tmp/test.mjs:6:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Comment by svvac** [comment]
Note that it can even break when not calling `AbortController.abort()`, for example when the signal gets many listeners added because of the warning emitted by node.

```javascript
import got from 'got';
const abortCtrl = new AbortController();
const got2 = got.extend({
    signal: abortCtrl.signal,
});

for (let i = 0; i < 50; i++) {
    abortCtrl.signal.addEventListener('abort', () => { /* noop */ });
}
```

```console
$ node test2.mjs
node:internal/event_target:423
      this[kMaxEventTargetListenersWarned] = true;
                                           ^

TypeError: Cannot assign to read only property 'Symbol(events.maxEventTargetListenersWarned)' of object '#<AbortSignal>'
    at AbortSignal.[kNewListener] (node:internal/event_target:423:44)
    at AbortSignal.[kNewListener] (node:internal/abort_controller:173:24)
    at AbortSignal.addEventListener (node:internal/event_target:535:23)
    at file:///tmp/test2.mjs:8:22
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

I suspect there might be other cases as well.
