### ISSUE TITLE
Got Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by darkprisco** [sindresorhus/got#2173]
Hi guys, 
 I am moving from **request** to **got** library, but in my tests I have observed something new that honestly I haven't seen in the past while I was using the previous library, I am sure there is something I am not configured properly.

Below what it is returned during my tests:

```
Nov 4 12:55:08 myservice-api-58c7687867-qqt7h myservice-api ERROR queryXACML Network ERROR: RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (file:///opt/app-root/src/node_modules/got/dist/source/core/index.js:773:107)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at LegacyContextManager.runInContext (/opt/app-root/src/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at ClientRequest.wrapped (/opt/app-root/src/node_modules/newrelic/lib/transaction/tracer/index.js:204:37)
    at ClientRequest.wrappedRequestEmit (/opt/app-root/src/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:143:26)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at /opt/app-root/src/node_modules/newrelic/lib/shim/shim.js:1313:22
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1590:19)
    at TLSSocket.emit (node:events:525:35)
    at /opt/app-root/src/node_modules/newrelic/lib/shim/shim.js:1313:22
    at LegacyContextManager.runInContext (/opt/app-root/src/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at Shim.applySegment (/opt/app-root/src/node_modules/newrelic/lib/shim/shim.js:1303:25)
    at TLSSocket.wrapper [as emit] (/opt/app-root/src/node_modules/newrelic/lib/shim/shim.js:1904:17)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at /opt/app-root/src/node_modules/newrelic/lib/shim/shim.js:1313:22
    at LegacyContextManager.runInContext (/opt/app-root/src/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23) {
  input: undefined,
  code: 'ECONNRESET',
  timings: {
    start: 1667562908060,
    socket: 1667562908060,
    lookup: 1667562908064,
    connect: 1667562908064,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1667562908071,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 4,
      tcp: 0,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 11
    }
  },
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: 10000,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: '[{"subject":{"accessTokenBody":"{{suspicious_text_redacted}}"},"resource":{"resource":"myresource","attributes":{"policyScopeSuffix":""}},"environment":{},"requestId":0,"action":"myservice.resource.read"}]',
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'got (https://github.com/sindresorhus/got)',
      'x-forwarded-by': 'myservice',
      authorization: '{{bearer_auth_redacted}}',
      accept: 'application/vnd.authz.v2+json',
      'transaction-id': 'gst-1ce97055-8fa0-4acb-b7d9-9a7de94295eb-0-0-0',
      'content-type': 'application/json',
      'content-length': '1430',
      'accept-encoding': 'gzip, deflate, br'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 2,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: 200,
      noise: 100
    },
    localAddress: undefined,
    method: 'POST',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'json',
    url: URL {
      href: 'https://mytest.com/v1/auth',
      origin: 'https://mytest.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'mytest.com',
      hostname: 'mytest.com',
      port: '',
      pathname: '/v1/auth',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined,
    signal: undefined,
    enableUnixSockets: true
  }
} 

```
Do you see something that could be the problem?
I was thinking that the retry mechanism was not working properly with https but this is not the case.

#### Checklist

- [x] I have read the documentation.

**Comment by szmarczak** [comment]
The server closed the connection forcibly. Most likely you're sending an HTTPS request to an HTTP server.

**Comment by darkprisco** [comment]
> The server closed the connection forcibly. Most likely you're sending an HTTPS request to an HTTP server.

No, my requests are performed towards an HTTPs server and it is happening randomly.

**Comment by szmarczak** [comment]
The issue is on the server side.

**Comment by szmarczak** [comment]
There are no issues. You could try enabling HTTP/2, maybe that'll help. Or try using keep-alive agents.

**Comment by darkprisco** [comment]
I think I got the problem, the retry logic is not applied for the **POST** requests.
If i would like to perform 3 retries for my **GET/POST** requests, which is the right configuration to be used?
I would like to have the first retry after 500ms and the others following an exponential backoff.

Could you suggest the configuration for such expected behavior? Below what I have applied
**{
  url: 'https://mytest.com',
  headers: { 'X-Forwarded-By': 1, 'Transaction-ID': 1 },
  method: 'POST',
  timeout: { request: 10000 },
  retry: { limit: 2, backoffLimit: 200 },
  json: 'test',
  responseType: 'json'
}**

**Comment by szmarczak** [comment]
This is correct, since payload can be read only once.
