### ISSUE TITLE
timeout and timings are not working?

### ISSUE THREAD

**Issue by ryohetoy** [sindresorhus/got#2174]
#### Describe the bug

 - Node.js version:  v16.13.1
 - OS & version: macOS 12.6

When I send many get requests, `timeout` and `response.timings` are not working as expected.

#### Actual behavior
I send around 500 get requests to different urls concurrently by using promise, `timings.dns` of each request is increasing. 

#### Expected behavior
`timings.dns` should show actual time.

#### Code to reproduce

```js
const got = require("got");

console.time('total');
const urlList = [
  "https://devblogs.microsoft.com/landingpage/", 
  "https://it.impress.co.jp/list/feed/rss", 
  "https://uxmilk.jp/feed",
  ... more 500 urls
];
const pList = urlList.map(function(url) {
    return got(url, {timeout: {request: 60000, }, retry: {limit: 0}}).then((result) => {
        const phases = result.timings.phases;
        const paheseResult = [url, phases.wait, phases.dns, phases.tcp, phases.tls, phases.request, phases.firstByte, phases.download, phases.total];
        console.log(paheseResult.join(","));
    }).catch((e) => {
        return null;
    });
});

Promise.all(pList).then((result) => {
    console.timeEnd('total');
}).catch((e) => {
    console.log('error: ' + e);
});
```

This is the graph which I made from each url's response.timings.
`dns` is increasing, so if I set timeout to 30s, most of requests fails.

<img width="740" alt="スクリーンショット 2022-11-07 21 31 40" src="https://user-images.githubusercontent.com/29276527/200311326-6c39d203-31e4-4737-bf09-1f389d606ac5.png">

Sorry if this is my misunderstanding because I'm new to node, thanks in advance!

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
It's unlikely that the timings are wrong. Can you try https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#dnscache

**Comment by ryohetoy** [comment]
@szmarczak 
Thank you for reply, but it's not changed.
`got(url, {timeout: {request: 60000, dnsCache: true}, retry: {limit: 0}})`

It looks like some connections are waiting for other connections to finish. Is there any connection limit setting?

**Comment by szmarczak** [comment]
You could try passing a custom agent. Also please try HTTP/2

**Comment by alexgalkin** [comment]
Node v16.18.0
macOS 11.16.8
npm 8.19.3

I have the issue with the timeout as well.  NOTE: the service is down in my case (there is noting running at http://localhost:3333)

Here is a basic example:

```
fastify.get('/', async function (request, reply) {
    try {
      console.log( {timings} = await got.get('http://localhost:3333', {timeout : { request : 500 }}))
      return {"result":"ok"}
    } catch(err) {
      throw err
    }
  })
```

and it took more than 3 seconds to return the response (when I expected that after 500 ms).

```
{
    "level":50,
    "time":1677166883697,
    "pid":34364,
    "hostname":"MPro.local",
    "reqId":"req-1",
    "req":{
        "method":"GET",
        "url":"/",
        "hostname":"localhost:3000",
        "remoteAddress":"::1",
        "remotePort":60559
    },
    "res":{
        "statusCode":500
    },
    "err":{
        "type":"RequestError",
        "message":"connect ECONNREFUSED 127.0.0.1:3333",
        "stack":"RequestError: connect ECONNREFUSED 127.0.0.1:3333\n    at ClientRequest.<anonymous> (/Users/alexgalkin/projects/training/node-services/labs/ch-7/labs-1/node_modules/got/dist/source/core/index.js:970:111)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.origin.emit (/Users/alexgalkin/projects/training/node-services/labs/ch-7/labs-1/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at Socket.socketErrorListener (node:_http_client:494:9)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)",
        "name":"RequestError",
        "code":"ECONNREFUSED",
        "timings":{
            "start":1677166883693,
            "socket":1677166883694,
            "lookup":1677166883695,
            "error":1677166883696,
            "phases":{
                "wait":1,
                "dns":1,
                "total":3
            }
        }
    },
    "msg":"connect ECONNREFUSED 127.0.0.1:3333"
}
```

I am wondering why it waits 3 seconds for ECONNREFUSED instead of returning ETIMEDOUT right after 500ms?
