### ISSUE TITLE
Usage with windows named pipes

### ISSUE THREAD

**Issue by prabhu** [sindresorhus/got#2178]
#### What would you like to discuss?

Any working examples use this library with named pipes. For eg, on Windows, docker API could be accessed over `npipe//./pipe/docker_engine:`. Currently getting `Invalid URL` error where as on UNIX this syntax works `unix:/var/run/docker.sock:`

```
TypeError: Invalid URL
          at new NodeError (node:internal/errors:393:5)
          at URL.onParseError (node:internal/url:565:9)
          at new URL (node:internal/url:645:5)
          at Object.<anonymous>.exports.default (E:\work\cdxgen\node_modules\got\dist\source\core\utils\options-to-url.js:35:17)
          at normalizeArguments (E:\work\cdxgen\node_modules\got\dist\source\core\index.js:486:51)
          at got (E:\work\cdxgen\node_modules\got\dist\source\create.js:112:39)
          at Function.get (E:\work\cdxgen\node_modules\got\dist\source\create.js:224:42)
          at getConnection (E:\work\cdxgen\docker.js:99:23)
          at makeRequest (E:\work\cdxgen\docker.js:150:22)
          at getImage (E:\work\cdxgen\docker.js:232:23) {
        input: 'npipe//./pipe/docker_engine:/_ping',
```
#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
Got is a HTTP client. Named pipes is out of scope. The Unix thing was added for convenience, but it also caused a lot of problems, so in hindsight, I would not have added it.
