### ISSUE TITLE
RequestError: The `body` option must be a stream.Readable, string or Buffer

### ISSUE THREAD

**Issue by ketavchotaliya** [sindresorhus/got#2198]
#### I am getting this error while trying to hit the POST, and PUT APIs.
_Software specifications:_
GOT: 11.8.6
OS: Windows 10
Node: 16.18.1
NPM: 8.19.2

_Code Snippet_
`const gotObject = {
            method: req.method,
            json: true,
            body: req.body,
            headers: reqHeader,
          };`
`const apiResponse = await got(microserviceUrl, gotObject);`

_Error Stack_
`2022-12-19T11:38:44.708Z - error: [D:\Projects\NodeJs\gateway\src\services\microservice.ts] callService 
    at Request._destroy (D:\Projects\NodeJs\node-api-gateway\node_modules\got\dist\source\core\index.js:1386:21)
    at _destroy (node:internal/streams/destroy:102:25)
    at Request.destroy (node:internal/streams/destroy:64:5)
    at D:\Projects\NodeJs\node-api-gateway\node_modules\got\dist\source\core\index.js:354:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Request._finalizeBody (D:\Projects\NodeJs\node-api-gateway\node_modules\got\dist\source\core\index.js:726:23)       
    at D:\Projects\NodeJs\node-api-gateway\node_modules\got\dist\source\core\index.js:333:28
    at new Request (D:\Projects\NodeJs\node-api-gateway\node_modules\got\dist\source\core\index.js:357:11)
    at makeRequest (D:\Projects\NodeJs\node-api-gateway\node_modules\got\dist\source\as-promise\index.js:35:29)`

#### Checklist

- [ ] I have read the ReadMe page but no specification is found on this.

**Comment by sindresorhus** [comment]
I would make sure that `req.body` is actually one of the supported types.

Also, Got 11 is no longer supported.

**Comment by ketavchotaliya** [comment]
@sindresorhus req.body is just a JSON object

**Comment by Caesarovich** [comment]
> Note: If `body` is specified, then the`json` or `form` option cannot be used.

[See doc](https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#note-7)

@ketavchotaliya what you want is to us the `json` option, not `body` if I'm not mistaken.
