### ISSUE TITLE
Build in China

### ISSUE THREAD

**Issue by smart2pet** [sindresorhus/got#2213]
#### Describe the bug

 - Node.js version: v16.18.1
 - OS & version: 22H2 Build 22623.1180

#### Actual behavior
Problem in building. Probably because google services are being blocked in China.
Output log:
```
node:events:491
      throw er; // Unhandled 'error' event
      ^
ErrorClass [RequestError]: connect ETIMEDOUT 142.251.42.225:443
    at ClientRequest.<anonymous> (D:\...\node_modules\got\index.js:73:21)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on DuplexWrapper instance at:
    at EventEmitter.emit (node:events:513:28)
    at ClientRequest.<anonymous> (D:\...\node_modules\got\index.js:73:7)
    at Object.onceWrapper (node:events:628:26)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ETIMEDOUT',
  host: 'clients2.googleusercontent.com',
  hostname: 'clients2.googleusercontent.com',
  method: 'GET',
```

#### Expected behavior
Building without errors in all regions.

#### Code to reproduce
Run `yarn install` in a computer that connects the network in China. And you'll got this error.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
I think you opened this in the wrong repo.

**Comment by smart2pet** [comment]
No. It's the code of this library.

**Comment by smart2pet** [comment]
at ClientRequest.<anonymous> (D:\...\node_modules\got\index.js:73:7)
                                                                 Look here:     ~~~
