### ISSUE TITLE
Browser app fail: TypeError: promisify4 is not a function

### ISSUE THREAD

**Issue by sysmat** [sindresorhus/got#2222]
#### Describe the bug

 - Node.js version:  v18.12.1
 - OS & version:  Windows 10
 - svelte: 3.55.1
 - vite: 4.1.1
 - "typescript": "^4.9.5"
 - "got": "^12.5.3",

#### Actual behavior

- browser dev console error log:

```
index.js:7 Uncaught (in promise) TypeError: promisify4 is not a function
    at node_modules/get-stream/index.js (index.js:7:35)
    at __require2 (chunk-YBOLLQGG.js?v=b4ac6210:16:50)
    at index.ts:7:23

```
#### Expected behavior

- To fetch from resource

#### Code to reproduce

```typescript
import got, { type ExtendOptions } from "got";

const apiUrl = 'https://jsonplaceholder.typicode.com' as const;
const token = 'aas.sdsdsds.ssdds' as const;

const options: ExtendOptions = {
    prefixUrl: apiUrl,
    headers: {
        Authorization: `Bearer ${token}`
    },
    timeout: {
        send: 3500
    },
};

const client = got.extend(options);

export const posts = async (): Promise<PostType[]> => {
    console.log('api:posts'); // not reachable
    return await client.get('/posts').json(); // not working
   
    // working when removing got
   // working with: ky, fetch
    //const r = await fetch(`${apiUrl}/posts`);
    //return r.json();
}

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
Got is for Node.js not the browser.

**Comment by sysmat** [comment]
@sindresorhus my mistake

> For browser usage, we recommend [Ky](https://github.com/sindresorhus/ky) by the same people.
