### ISSUE TITLE
Catch ECONNREFUSED Error

### ISSUE THREAD

**Issue by Ocean15** [sindresorhus/got#2275]
#### What would you like to discuss?

Hello there. I'm calling my own api for a healthcheck. Obviously getting a "ECONNREFUSED" error when the api isn't available. But I can't catch the error. Whatever and wherever I try to catch the error, it still throws `Uncaught exception: Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)`

This is basically what I'm doing, but the exception is still "uncaught":

`try {
await got.get("http://localhost:4000");
} catch(error) {
console.log("TEST")
}
`

What am I doing wrong here?

#### Checklist

- [X ] I have read the documentation.

**Comment by sindresorhus** [comment]
Can you run `node` with the `--trace-warnings` to get a stack trace?

**Comment by Ocean15** [comment]
Node is already running with trace-warnings flag. That's all stack trace we've got :(

**Comment by Ocean15** [comment]
Without catching anything I get `Uncaught exception: RequestError: socket hang up
    at ClientRequest.<anonymous> (file:///XXXXXXXXX/node_modules/got/dist/source/core/index.js:792:107)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at Socket.socketCloseListener (node:_http_client:469:11)
    at Socket.emit (node:events:525:35)
    at connResetException (node:internal/errors:718:14)
    at Socket.socketCloseListener (node:_http_client:469:25)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:320:12)
`

**Comment by 2snEM6** [comment]
This is happening to me as well when mocking an API with `msw` and returning a network error:

```typescript
import { graphql, HttpResponse, http } from 'msw';
import { setupServer } from 'msw/node';
import { got } from 'got';

let networkErrorCounter = 0;

const handlers = [
  http.get('https://unstable.com/v1/network-error', () => {
    if (networkErrorCounter === 0) {
      networkErrorCounter += 1;

      return HttpResponse.error();
    }

    return new HttpResponse(null, {
      status: 200,
    });
  }),
];

const server = setupServer(...handlers);

describe('got tests', () => {
    beforeAll(() => server.listen());
    afterEach(() => server.resetHandlers());
    afterAll(() => server.close());

    it('should retry requests on network error', async () => {
      const result = await got.get('https://unstable.com/v1/network-error');
      expect(result.statusCode).toBe(200);
      expect.assertions(1);
    });
});
```

Fails when running `npx vitest` with:

```
Error: socket hang up
 ❯ connResetException node:internal/errors:717:14
 ❯ _destroy node:_http_client:880:15
 ❯ TLSSocket.<anonymous> node:_http_client:897:11
 ❯ TLSSocket.<anonymous> node:internal/util:464:12
 ❯ onclose node:internal/streams/end-of-stream:148:25
 ❯ processTicksAndRejections node:internal/process/task_queues:77:11
 ```
 
 
![image](https://github.com/sindresorhus/got/assets/7485885/7a888f60-06b0-4219-891b-25bfa1731bc1)

**Comment by 2snEM6** [comment]
I am happy to provide a fully working reproducible example if needed but the above code snippet should work

**Comment by try-to-fly** [comment]
same for me,  cannot catch this error
```
 unhandledRejection socket hang up RequestError: socket hang up
    at ClientRequest.<anonymous> (file:///C:/Users/admin/AppData/Local/pnpm/global/5/.pnpm/got@14.2.0/node_modules/got/dist/source/core/index.js:670:107)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:530:35)
    at ClientRequest.emit (node:domain:488:12)
    at Socket.socketOnEnd (node:_http_client:519:9)
    at Socket.emit (node:events:530:35)
    at Socket.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at connResetException (node:internal/errors:787:14)
    at Socket.socketOnEnd (node:_http_client:519:23)
    at Socket.emit (node:events:530:35)
    at Socket.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
