### ISSUE TITLE
Useless stack traces

### ISSUE THREAD

**Issue by paulius-valiunas** [sindresorhus/got#2277]
#### Describe the bug

 - Node.js version: 18.16.0
 - OS & version: Debian Bullseye

When a request times out, got throws an error with a useless stack trace that doesn't have a single frame from my code.

#### Actual behavior

```
RequestError: Timeout awaiting 'connect' for 200ms
    at ClientRequest.<anonymous> (/app/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:65)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at origin.emit (/app/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at Timeout.timeoutHandler [as _onTimeout] (/app/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:571:11)
    at process.processTimers (node:internal/timers:512:7)
```

#### Expected behavior

A stack trace that gives me information on which request failed and where in my code I made the request.

#### Code to reproduce

```js
await got("https://google.com");
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by paulius-valiunas** [comment]
note that some of our projects are stuck with CJS so we can't update to got@12 everywhere

**Comment by sindresorhus** [comment]
Got v11 is no longer supported. There will be no changes to v11.

**Comment by TonyRL** [comment]
RequestError: Timeout awaiting 'connect' for **200ms**

Did you set the timeout too short?
