### ISSUE TITLE
Bun throws error 'A retry listener has been attached already'

### ISSUE THREAD

**Issue by iamkhalidbashir** [sindresorhus/got#2299]
[Bun](https://bun.sh) throws error on this line

https://github.com/sindresorhus/got/blob/944caa8ce8151d7b18ab17c4130b18d622c04ebe/source/core/index.ts#L219C3-L224C1

**Comment by sindresorhus** [comment]
If this only happens on Bun and not Node.js, you need to report it in the Bun issue tracker. They claim Node.js compatibility, so they need to resolve any Node.js compatibility issues.

**Comment by iamkhalidbashir** [comment]
It makes sense, you can close this if you'd like
but I think its a small fix as all of other packages dosent give an issue with bun
so if you could look into it, would appreciate it.

**Comment by bryanjtc** [comment]
Does 1.0.13 fix the issue?

**Comment by Thinkscape** [comment]
> Does 1.0.13 fix the issue?

nope :(

**Comment by prabhu** [comment]
With got 14.3.0, I am getting

```
767 |             const cacheRequest = cacheableStore.get(options.cache)(options, async (response) => {
768 |                 response._readableState.autoDestroy = false;
769 |                 if (request) {
770 |                     const fix = () => {
771 |                         if (response.req) {
772 |                             response.complete = response.req.res.complete;
                                                      ^
TypeError: undefined is not an object (evaluating 'response.req.res.complete')
      at fix (/home/runner/work/cdxgen/cdxgen/node_modules/got/dist/source/core/index.js:772:49)
      at /home/runner/work/cdxgen/cdxgen/node_modules/got/dist/source/core/index.js:776:21
      at /home/runner/work/cdxgen/cdxgen/node_modules/got/dist/source/core/index.js:767:84
      at /home/runner/work/cdxgen/cdxgen/node_modules/cacheable-request/dist/index.js:148:25
      at handler (/home/runner/work/cdxgen/cdxgen/node_modules/cacheable-request/dist/index.js:77:40)
      at node:http:930:191
```

**Comment by TheOrdinaryWow** [comment]
any update till now?
