### ISSUE TITLE
Failing with deno

### ISSUE THREAD

**Issue by kesavkolla** [sindresorhus/got#2387]
#### Describe the bug

 - Deno version: deno 2.0.3 (stable, release, x86_64-unknown-linux-gnu)
 - OS & version: Linux

#### Actual behavior
Uncaught RequestError: The "listener" argument must be of type function. Received an instance of Object
    at Request._beforeError (file:///home/kesav/.cache/deno/npm/registry.npmjs.org/got/14.4.3/dist/source/core/index.js:183:21)
    at Request.flush (file:///home/kesav/.cache/deno/npm/registry.npmjs.org/got/14.4.3/dist/source/core/index.js:172:18)
    at __node_internal_ (ext:deno_node/internal/validators.mjs:283:13)
    at checkListener (ext:deno_node/_events.mjs:116:3)
    at HttpsClientRequest.once (ext:deno_node/_events.mjs:537:3)
    at new ClientRequest (node:http:172:12)
    at new HttpsClientRequest (node:https:73:79)
    at request (node:https:123:10)
    at Request._makeRequest (file:///home/kesav/.cache/deno/npm/registry.npmjs.org/got/14.4.3/dist/source/core/index.js:838:37)
    at Request.flush (file:///home/kesav/.cache/deno/npm/registry.npmjs.org/got/14.4.3/dist/source/core/index.js:158:24)
    at eventLoopTick (ext:core/01_core.js:175:7)
...

#### Expected behavior
The text from the request
...

#### Code to reproduce

```js
import {got} from 'npm:got';
await got.get('https://www.google.com').text()
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by katsanva** [comment]
Not reproducible on deno@2.0.4 and got@14.4.3. Please update on your side.

**Comment by Morb0** [comment]
Upgrade Deno solved issue
