### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by wayneashleyberry** [sindresorhus/got#313]
I get the following error, even though I'm catching my requests.

> (node:32979) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): HTTPError: Response code 404 (Not Found)
(node:32979) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Here's a test case:

```js
const got = require('got');

const request = got('https://www.google.com/foo/bar');

// process.on('unhandledRejection', function(reason, p){
// 	console.log("Possibly Unhandled Rejection at: Promise ", p, " reason: ", reason);
// });

request.then((response) => {
	//
});

request.catch((err) => {
	//
});
```

Here's the stack trace when I catch the events:

```
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { HTTPError
    at stream.catch.then.data (/Users/wayne/Desktop/test-case/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  message: 'Response code 404 (Not Found)',
  host: 'www.google.com',
  hostname: 'www.google.com',
  method: 'GET',
  path: '/foo/bar',
  statusCode: 404,
  statusMessage: 'Not Found' } }  reason:  { HTTPError
    at stream.catch.then.data (/Users/wayne/Desktop/test-case/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  message: 'Response code 404 (Not Found)',
  host: 'www.google.com',
  hostname: 'www.google.com',
  method: 'GET',
  path: '/foo/bar',
  statusCode: 404,
  statusMessage: 'Not Found' }
```

**Comment by wayneashleyberry** [comment]
I'm using node `v7.10.0`

**Comment by kevva** [comment]
You need to chain them:

```js
request
    .then(res => {
        console.log(res);
    })
    .catch(err => {
        console.log(err);
    });
```

**Comment by wayneashleyberry** [comment]
@kevva out of interest, why? I've used a ton of promises without chaining like that before.

**Comment by kevva** [comment]
The following code will also result in a unhandled rejection:

```js
const p = new Promise((resolve, reject) => {
    reject(new Error('This is so much error'));
});

p.catch(err => {
    console.log(err);
});

p.then(() => {
    console.log('resolved');
});
```

**Comment by sindresorhus** [comment]
What @kevva said. It's because those statements create two new promise flows, and the last one doesn't have a catch handler.
