### ISSUE TITLE
Got module fails with Shopify api unless multiple requests are sent

### ISSUE THREAD

**Issue by Sharma-Rajat** [sindresorhus/got#338]
Using the **got module** with the **shopify API** fails if you attempt to send multiple async requests without waiting for the response of the initial request.

If you send one request: SUCCESS
if you send two requests: FAIL, SUCCESS
if you send three requests: FAIL, SUCCESS, FAIL
and so on. 

Example cases described in the code below. Each case should be executed in it's own file.

See javascript below.:
```
const fs = require('fs');
const got = require('got');

function createProduct() {
    return got.post('test-shop.myshopify.com/admin/products.json', {
        headers: {
            'User-Agent': 'shopify-api-node/2.4.0',
            'Content-Type': 'application/json'
        },
        timeout: 60000,
        json: true,
        retries: 0,
        method: 'POST',
        path: '/admin/products.json',
        auth: 'user:pass',
        hostname: 'test-shop.myshopify.com',
        protocol: 'https:',
        body: {
            "product": {
                "title": "Burton Custom Freestyle 151",
                "body_html": "<strong>Good snowboard!<\/strong>",
                "vendor": "Burton",
                "product_type": "Snowboard",
                "published": false
            }
        }
    }).then(response => {
        console.log(response.body);
        //=> '<!doctype html> ...'
    });
}
```
```
//
// EXAMPLE 1
//

//success
createProduct().catch(error => {
    console.log('error 2: ');
    console.log(error);
});
```
```
//
// EXAMPLE 2
//
//

//success 
createProduct()
    .catch(error => {
        console.log('error 2: ');
        console.log(error);
    })
    .then(() => createProduct())
    .catch(error => {
        console.log('error 2: ');
        console.log(error);
    });
```
```
//
// EXAMPLE 3
//

//failed
createProduct()
    .catch(error => {
        console.log('error 2: ');
        console.log(error);
    })
createProduct()
    .catch(error => {
        console.log('error 2: ');
        console.log(error);
    });
```
the actual error that is thrown is:

```
{ HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.data (D:\WebDev\Jonar\gotrrr\node_modules\got\index.js:176:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'HTTPError',
  host: 'test-shop.myshopify.com',
  hostname: 'test-shop.myshopify.com',
  method: 'POST',
  path: '/admin/products.json',
  protocol: 'https:',
  url: 'http://test-shop.myshopify.com/admin/products.json',
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers:
   { server: 'nginx',
     date: 'Mon, 19 Jun 2017 14:51:35 GMT',
     'content-type': 'application/json; charset=utf-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'x-sorting-hat-podid': '15',
     'x-sorting-hat-podid-cached': '1',
     'x-sorting-hat-shopid': '18149403',
     'x-sorting-hat-section': 'pod',
     'x-sorting-hat-shopid-cached': '1',
     'referrer-policy': 'origin-when-cross-origin',
     'x-frame-options': 'DENY',
     'x-shopid': '18149403',
     'x-shardid': '15',
     'x-shopify-shop-api-call-limit': '1/40',
     http_x_shopify_shop_api_call_limit: '1/40',
     'x-stats-userid': '0',
     'x-stats-apiclientid': '1564783',
     'x-stats-apipermissionid': '43176901',
     'x-request-id': 'd30d6b9f-ec34-4011-af13-7b8187dccbe5',
     'content-security-policy': 'default-src \'self\' data: blob: \'unsafe-inline\' \'unsafe-eval\' https://* shopify-pos://*; block-all-mixed-content; child-src \'self\' https://* shopify-pos://*; connect-src \'self\' wss://* https://*; script-src https://cdn.shopify.com https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://dme0ih8comzn4.cloudfront.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://maps.googleapis.com https://stats.g.doubleclick.net https://www.google-analytics.com https://visitors.shopify.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com \'self\' \'unsafe-inline\' \'unsafe-eval\'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=create&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin&source%5Buuid%5D=d30d6b9f-ec34-4011-af13-7b8187dccbe5',
     'x-content-type-options': 'nosniff',
     'x-download-options': 'noopen',
     'x-permitted-cross-domain-policies': 'none',
     'x-xss-protection': '1; mode=block; report=/xss-report?source%5Baction%5D=create&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin&source%5Buuid%5D=d30d6b9f-ec34-4011-af13-7b8187dccbe5',
     'x-dc': 'ash' } }
```
Running the examples above with the **request module** works in all cases.

**Comment by kevva** [comment]
Can you log `err.response.body`? Looks like it's something wrong with your request body.
