### ISSUE TITLE
Https protocol bug

### ISSUE THREAD

**Issue by slavaGanzin** [sindresorhus/got#403]
Hello, @sindresorhus.

I have this weird protocol handshake alert:
```
 got('www.maa.org').then(console.log).catch(console.log)
> { RequestError: write EPROTO 140593356778368:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:772:

    at ClientRequest.req.once.err (/home/vganzin/work/pipeline/node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:408:12)
    at onwrite (_stream_writable.js:430:5)
    at _destroy (internal/streams/destroy.js:39:7)
  name: 'RequestError',
  code: 'EPROTO',
  host: 'www.maa.org',
  hostname: 'www.maa.org',
  method: 'GET',
  path: '/',
  protocol: 'https:',
  url: 'https://www.maa.org/' }
```

Maybe you may know what does it mean?

**Comment by sindresorhus** [comment]
I don't think this is Got's fault: https://www.google.com/search?q=write+EPROTO

**Comment by Freakachoo** [comment]
I'm using Node version 12.4.0 still having the same error

```
[error] GotError: write EPROTO 139716681226048:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 40

    at onError (/home/node/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/node/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
```

**Comment by szmarczak** [comment]
This is not a bug

**Comment by Freakachoo** [comment]
@szmarczak do you know, maybe, any workaround regarding this?
When I'm doing the same https requests with using `request` module it works well. Maybe you know the root cause of it? Need some help here, please

**Comment by szmarczak** [comment]
No, the issue is on the server side.
