### ISSUE TITLE
Request continues after cancellation

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#462]
```javascript
const got = require('got');

(async function() {
	var promise = got('https://goo.gl/iiJ61G').on('redirect', resp => {
		console.log('Cancelling: ', resp.url);
		promise.cancel();
	}).on('downloadProgress', progress => {
		console.log(progress);
	});

	try {
		var request = await promise;
	} catch (e) {
		console.log(e);
	}
	
	console.log('Da end.');
})();
```

The following gives:
```
Cancelling:  https://goo.gl/iiJ61G
{ CancelError: Promise was canceled
    at PCancelable.cancel (C:\Users\Szymon Marczak\Desktop\ak server\node_modules\p-cancelable\index.js:66:16)
    at EventEmitter.got.on.resp (C:\Users\Szymon Marczak\Desktop\ak server\test.js:6:11)
    at EventEmitter.emit (events.js:159:13)
    at EventEmitter.emit (events.js:159:13)
    at res (C:\Users\Szymon Marczak\Desktop\ak server\node_modules\got\index.js:138:8)
    at ClientRequest.handler (C:\Users\Szymon Marczak\Desktop\ak server\node_modules\cacheable-request\src\index.js:88:7)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23) name: 'CancelError' }
Da end.
Cancelling:  http://google.pl/
{ percent: 0, transferred: 0, total: 5001 }
{ percent: 0.14917016596680663, transferred: 746, total: 5001 }
{ percent: 0.7210557888422315, transferred: 3606, total: 5001 }
{ percent: 0.9630073985202959, transferred: 4816, total: 5001 }
{ percent: 1, transferred: 6211, total: 5001 }
{ percent: 1, transferred: 16726, total: 5001 }
```

I think it should *really* abort the request.

Calling `promise.cancel()` -> `req.abort()` makes an error:
```javascript
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:164:20)
    at TCP._handle.close [as _onclose] (net.js:558:12) code: 'ECONNRESET' }
```
which is catched [here](https://github.com/sindresorhus/got/blob/master/index.js#L210). Unfortunately, the request carries on because of [here](https://github.com/floatdrop/is-retry-allowed/blob/master/index.js#L5). It doesn't know who has hanged up, we or the server...

**Comment by szmarczak** [comment]
@sindresorhus could you look at this?
