### ISSUE TITLE
Using Nock with delay: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by sampok** [sindresorhus/got#476]
Using [Nock](https://github.com/node-nock/nock) with delays worked fine with got 8.2.0 and earlier, but now with 8.3.0 throws error:

```
const got = require("got"); // v.8.3.0
const nock = require("nock"); // v.9.2.3
const url = "https://google.com/";

(async () => {
  // 1. Without delay works fine
  const nock1 = nock(url)
    .get("/")
    .reply(200);
  await got(url);

  // 2. With delay: Error
  const nock2 = nock(url)
    .get("/")
    .delay(1000)
    .reply(200);
  await got(url); // TypeError [ERR_INVALID_ARG_TYPE]...
})();
```

Error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type null
    at Function.byteLength (buffer.js:502:11)
    at Timeout.setInterval [as _onTimeout] (/Users/sampo/Codeland/got-nock-bug/node_modules/got/index.js:202:35)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by mnmkng** [comment]
I can confirm that I'm getting the same error, in an unrelated use case. For me, the `byteLength` function fails randomly when I receive a RequestError:

```
[-] RequestError: getaddrinfo ENOTFOUND xxx.net xxx.net:443
    RequestError: getaddrinfo ENOTFOUND xxx.net xxx.net:443
        at ClientRequest.req.once.err (.../node_modules/got/index.js:220:22)
        at Object.onceWrapper (events.js:315:30)
        at emitOne (events.js:121:20)
        at ClientRequest.emit (events.js:211:7)
        at TLSSocket.socketErrorListener (_http_client.js:387:9)
        at emitOne (events.js:116:13)
        at TLSSocket.emit (events.js:211:7)
        at emitErrorNT (internal/streams/destroy.js:64:8)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
```

Which is correct, I purposefully hit a nonexistent URL to isolate the problem.

The server will die with:

```
buffer.js:481
    throw new TypeError('"string" must be a string, Buffer, or ArrayBuffer');
    ^

TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at Timeout.setInterval [as _onTimeout] (.../node_modules/got/index.js:202:35)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

The reason for `byteLength` throwing is the fact that `req._headers` are `null`.

Downgrading to 8.2.0 fixes the issue.

Thanks for looking into it.

**Comment by Rowno** [comment]
Looks like #469 didn't fix the issue.

**Comment by sindresorhus** [comment]
@szmarczak has confirmed that Nock now works with the latest code in master.
