### ISSUE TITLE
Redirection to a malformed URI crashes whole process

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#494]
Demo:
```javascript
const got = require('got');

(async function() {
    try {
        var response = await got('http://shorturl.at/dsDT8'); // redirects to https://google.com/%D8
    } catch (e) {
        console.log('caught:', e);
    }

    console.log('it should display this');
})();
```

Result:
```bash
$ node blah
/home/szymon/Desktop/server/node_modules/normalize-url/index.js:85
                urlObj.pathname = decodeURI(urlObj.pathname);
                                  ^

URIError: URI malformed
    at decodeURI (<anonymous>)
    at module.exports (/home/szymon/Desktop/server/node_modules/normalize-url/index.js:85:21)
    at /home/szymon/Desktop/server/node_modules/cacheable-request/src/index.js:43:16
    at get (/home/szymon/Desktop/server/node_modules/got/index.js:98:20)
    at res (/home/szymon/Desktop/server/node_modules/got/index.js:140:5)
    at ClientRequest.handler (/home/szymon/Desktop/server/node_modules/cacheable-request/src/index.js:88:7)
    at Object.onceWrapper (events.js:275:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:534:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

There are two possible solutions:
~1. Support malformed URIs.~
2. Throw an error.

~I would recommend the first solution, because you're able to visit `https://google.com/%D8` in browser, even more: you can make a request to that using `http`/`https` module!~

~Because that's upstream issue, I suggest adding a new option: `throwsOnMalformedURI` which is `true` by default.~

EDIT: the first solution would cause too many problems. It should throw a Got error.

**Comment by sindresorhus** [comment]
Can you also open an issue on `cacheable-request`? It seems it's not properly catching and propagating all errors.

**Comment by szmarczak** [comment]
I'm not sure if you're talking about errors thrown by [callback](https://github.com/lukechilds/cacheable-request/blob/18df2e8893ba48bb462083d4d989fdd4d5006433/src/index.js#L88) on `cacheable-request` side. Yeah, it could be caught and emitted, it's author's choice.
