### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by przemyslawpluta** [sindresorhus/got#604]
As per below example domain redirects `302` to invalid host name empty `http://` this breaks `got` and throws `UnhandledPromiseRejectionWarning` regardless of any attempt to `catch` errors.

```js
const got = require('got');

(async () => {
    try {
        const response = await got('fashion-bcom-prod.herokuapp.com');
        console.log(response.body);
    } catch (error) {
        console.log(error.response.body);
    }
})();
```

```bash
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at cacheableRequest (/wvp/node_modules/got/source/request-as-event-emitter.js:123:20)
    at ClientRequest.handler (/wvp/node_modules/cacheable-request/src/index.js:118:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.origin.emit.args [as emit] (/wvp/node_modules/@szmarczak/http-timer/source/index.js:36:11)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21) input: '//' } }  reason:  { TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at cacheableRequest (/wvp/node_modules/got/source/request-as-event-emitter.js:123:20)
    at ClientRequest.handler (/wvp/node_modules/cacheable-request/src/index.js:118:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.origin.emit.args [as emit] (/wvp/node_modules/@szmarczak/http-timer/source/index.js:36:11)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21) input: '//' }
```

**Comment by alextes** [comment]
Sadly I hit my time limit for this issue.

I have a fix, but sadly no test.
To clarify, got sends a request, a redirect comes back, the redirect neatly contains a `Location: //` header as it should, but the location is not a valid URL. Bad server 🙅‍♀️! 

So got tries to helpfully redirect but in constructing the redirect URL blows up.
Fix is:
```diff
diff --git a/source/request-as-event-emitter.js b/source/request-as-event-emitter.js
index 3187657..6bb9454 100644
--- a/source/request-as-event-emitter.js
+++ b/source/request-as-event-emitter.js
@@ -120,7 +120,12 @@ module.exports = options => {
                                }

                                const bufferString = Buffer.from(response.headers.location, 'binary').toString();
-                               redirectUrl = (new URL(bufferString, urlLib.format(options))).toString();
+                               try {
+                                       redirectUrl = (new URL(bufferString, urlLib.format(options))).toString();
+                               } catch (error) {
+                                       emitter.emit('error', new RequestError(error, options));
+                                       return;
+                               }

                                try {
                                        decodeURI(redirectUrl);
```

Sadly, in trying to write the test for it I've gotten stuck on figuring out why the test gets stuck. The following hangs:
```js
test.only('bad URL should not result in unhandled exception', async t => {
	await t.throwsAsync(() => got('//'));
})
```

Do the same in Node: `got('//')` and you immediately receive an unhandled rejection. 

For the one adding in a proper test here's what I have so far, it includes a quick curl exec to verify the new `/invalid-redirect` route is working.

Add this to the `test/arguments.js` server setup:
```js
	s.on('/invalid-redirect', (_, response) => {
		response.writeHead(302, {
			Location: '//'
		});
		response.end();
	});
```

Test
```js
const {exec} = require('child_process');

test('bad redirect should not result in unhandled exception', async t => {
	console.log(s.url)
	exec(`curl -sLD - ${s.url}/invalid-redirect`, (error, stdout) => {
		console.log('cURL ERR\n', error)
		console.log('cURL OUT\n', stdout);
	});
	await t.throwsAsync(() => got(`${s.url}/invalid-redirect`));
});
```
