### ISSUE TITLE
Using url options object results in Unsupported protocol "https"

### ISSUE THREAD

**Issue by SleeplessByte** [sindresorhus/got#609]
| | version |
| -- | -- |
| node --experimental-modules | 10.5 |
|  got | 9.2.1 |
| agentkeepalive | 3.5.1 |

When `got` is called with one argument `url` which is a `request.options` object, as defined in the README.md as _The URL to request, as a string, a https.request options object, or a WHATWG URL._, requests are failing given the following example:

Given these options
```JavaScript
import got from 'got'
import HttpAgent from 'agentkeepalive'

const AGENT_OPTIONS = {}
const IN_MEMORY_CACHE = new Map()

const DEFAULT_AGENTS = {
  http: new HttpAgent(AGENT_OPTIONS),
  https: new HttpAgent.HttpsAgent(AGENT_OPTIONS)
}
````

And executing this code with this `options` object
```JavaScript
let options = {
    protocol: 'https'
    port: 3003,
    hostname: 'example.org',
    path: '/path-to-test',
    headers: {
      accept: 'application/vnd.d.tld.mt+json, application/vnd.d.tld.errors.v1+json; q=0.1',
    },
  }
```

```JavaScript
const requestOptions = {
  method: 'GET',
  connection: 'keep-alive',
  agent: DEFAULT_AGENTS,
  timeout: AGENT_OPTIONS.timeout,
  cache: IN_MEMORY_CACHE,
  ...options,
}

got(requestOptions)
// UnsupportedProtocolError: Unsupported protocol "https"
```
The error goes away if I extract the `{ protocol, hostname, port, path }` from options and construct a url for example like this:
 
```Javascript
const { protocol, hostname, port, path, ...otherOptions } = requestOptions 
const url =  `${protocol}://${hostname}:${port}${path}`

got(url, otherOptions )
```

I don't think https or http should ever be unsupported. Additionally I tried to just set the https agent directly (dropping the map), and that does not change anything.

**Comment by szmarczak** [comment]
Could you paste stacktrace here?

**Comment by SleeplessByte** [comment]
```
Trace: { 
  UnsupportedProtocolError: Unsupported protocol "https"
    at get (...\repo\node_modules\got\source\request-as-event-emitter.js:37:26)
    at Immediate.setImmediate (...\repo\node_modules\got\source\request-as-event-emitter.js:227:10)
  name: 'UnsupportedProtocolError',
  host: undefined,
  hostname: 'example.org',
  method: 'POST',
  path: '/api/removed/for/issue',
  socketPath: undefined,
  protocol: 'https',
  url: undefined 
}
```

**Comment by szmarczak** [comment]
```
let options = {
    protocol: 'https'
    port: 3003,
    hostname: 'example.org',
    path: '/path-to-test',
    headers: {
      accept: 'application/vnd.d.tld.mt+json, application/vnd.d.tld.errors.v1+json; q=0.1',
    },
  }
```

Invalid protocol. It should be "https:"
