### ISSUE TITLE
RequestError: argument should be a Buffer

### ISSUE THREAD

**Issue by ninox92** [sindresorhus/got#623]
node: v8.12.0
OS: ubuntu 14.04
got: v9.2.1

cacheable-request seems to cache the PUT request and when you make the second request it throws an error.

```
{ RequestError: argument should be a Buffer
    at EventEmitter.cacheReq.on.error (got/source/request-as-event-emitter.js:155:27)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at makeRequest (cacheable-request/src/index.js:126:9)
    at get (cacheable-request/src/index.js:136:14)
    at <anonymous>
  name: 'RequestError',
  host: 'somehost.com',
  hostname: 'somehost.com',
  method: 'PUT',
  path: '/endpoint',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://somehost.com/endpoint' }
```

```
const got = require('got');

(async () => {
    try {
        const data = 'foo';
        const options = {
            headers: {
                'Content-Type': 'text/plain',
                'Content-Length': Buffer.byteLength(data)
            },
            method: 'PUT',
            cache: false,
            body: Buffer.from(data)
        };
        await got.put('/endpoint', options);
        await got.put('/endpoint', options);
    } catch (error) {
        console.error(error);
    }
})();

```

**Comment by szmarczak** [comment]
I've checked it myself and it works correctly on Got 9.2.2 without any errors.
