### ISSUE TITLE
MaxRedirectsError when accessing throught corporate proxy and receiving 301 redirect

### ISSUE THREAD

**Issue by lathil** [sindresorhus/got#626]
Hello

I have a probleme accessing a resource with Got on raw.github.com throught a corporate proxy.  Access throught proxy is ok, but GitHub reply by a 301 toward raw.githubusercontent.com, and then it look like got try more than 10 time to reply to the redirect and fails.

The version of Got is 7.1.0, Node is 10.8, NPM is 6.2.0

The Npm package that I try to load is the following, trace included:
```
./npm install pngquant-bin@4.0.0 --https-proxy=http://proxy-tech:9090 --proxy=http://proxy-tech:9090
> pngquant-bin@4.0.0 postinstall /base/usinededev/production/current/jenkins/workspace/dat-devops-2017/front/dat-front/target/node/node_modules/pngquant-bin
> node lib/install.js

  ¿ getaddrinfo ENOTFOUND raw.github.com raw.github.com:443
  ¿ pngquant pre-build test failed
  ¿ compiling from source
  ¿ pngquant pre-build test passed successfully
  ¿ MaxRedirectsError: pngquant failed to build, make sure that libpng-dev is installed
    at ClientRequest.fn.request.res (/base/usinededev/production/current/jenkins/workspace/dat-devops-2017/front/dat-front/target/node/node_modules/got/index.js:69:23)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:432:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
npm WARN enoent ENOENT: no such file or directory, open '/base/usinededev/production/current/jenkins/workspace/dat-devops-2017/front/dat-front/target/node/package.json'
```

Line 69 is when the exceptions is thrown in Got:
```
if (redirects.length >= 10) {
					ee.emit('error', new got.MaxRedirectsError(statusCode, redirects, opts), null, res);
					return;
}
```

I have the problem on a RedHad 6 x64 server.  I don't have the probleme on a Windows 7 developper machine, althought this one is going through a corporate proxy as well.

I have tested the same access with curl on the same RedHat server, that works ok, trace is below:
```
pvld0001:/home/udd>curl -x http://proxy-tech:9090  -verbose https://raw.github.com/imagemin/pngquant-bin/v4.0.0/vendor/linux/x64/pngquant -L
* About to connect() to proxy proxy-tech port 9090 (#0)
*   Trying 172.17.200.58... connected
* Connected to proxy-tech (172.17.200.58) port 9090 (#0)
* Establish HTTP proxy tunnel to raw.github.com:443
> CONNECT raw.github.com:443 HTTP/1.1
> Host: raw.github.com:443
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=www.github.com,O="GitHub, Inc.",L=San Francisco,ST=California,C=US
*       start date: Mar 23 00:00:00 2017 GMT
*       expire date: May 13 12:00:00 2020 GMT
*       common name: www.github.com
*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /imagemin/pngquant-bin/v4.0.0/vendor/linux/x64/pngquant HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: raw.github.com
> Accept: */*
> Referer: rbose
>
< HTTP/1.1 301 Moved Permanently
< Location: https://raw.githubusercontent.com/imagemin/pngquant-bin/v4.0.0/vendor/linux/x64/pngquant
< Content-Length: 0
< Accept-Ranges: bytes
< Date: Thu, 04 Oct 2018 12:48:36 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-cdg20721-CDG
< X-Cache: MISS
< X-Cache-Hits: 0
< Vary: Accept-Encoding
< X-Fastly-Request-ID: 9910752b5606f063b6071960e6c684fc48188d8c
<
* Connection #0 to host proxy-tech left intact
* Issue another request to this URL: 'https://raw.githubusercontent.com/imagemin/pngquant-bin/v4.0.0/vendor/linux/x64/pngquant'
* About to connect() to proxy proxy-tech port 9090 (#1)
*   Trying 172.17.200.58... connected
* Connected to proxy-tech (172.17.200.58) port 9090 (#1)
* Establish HTTP proxy tunnel to raw.githubusercontent.com:443
> CONNECT raw.githubusercontent.com:443 HTTP/1.1
> Host: raw.githubusercontent.com:443
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=www.github.com,O="GitHub, Inc.",L=San Francisco,ST=California,C=US
*       start date: Mar 23 00:00:00 2017 GMT
*       expire date: May 13 12:00:00 2020 GMT
*       common name: www.github.com
*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /imagemin/pngquant-bin/v4.0.0/vendor/linux/x64/pngquant HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: raw.githubusercontent.com
> Accept: */*
> Referer: rbose
>
< HTTP/1.1 200 OK
< Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< ETag: "b9d5e78bd506a86f06f9a8a070fb3f0c17b99e5a"
< Content-Type: application/octet-stream
< Cache-Control: max-age=300
< X-Geo-Block-List:
< X-GitHub-Request-Id: 1D26:3234:13D6FA:170211:5BB60C23
< Content-Length: 120648
< Accept-Ranges: bytes
< Date: Thu, 04 Oct 2018 12:48:36 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-cdg20751-CDG
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1538657317.694335,VS0,VE96
< Vary: Authorization,Accept-Encoding
< Access-Control-Allow-Origin: *
< X-Fastly-Request-ID: 88f37acd9010a8fac82387cd12a85e5535d1af8e
< Expires: Thu, 04 Oct 2018 12:53:36 GMT
< Source-Age: 0
<
... binary follow here
```

Do you have any experience or idea of such a probleme ?

Thanks

**Comment by sindresorhus** [comment]
Got doesn't support proxies out of the box, so this is more likely a problem with https://github.com/kevva/download which the `pngquant-bin` package depends on.

**Comment by lathil** [comment]
Yes, had a look at Download which setup a kind of proxy agent with Caw in the opts it provide to Got. That why the connection is setup correctly through the corporate proxy initialy toward raw.github.com.  It just that it is looping 10x time between

const get = opts => {
..
const req = fn.request(opts, res => {
.. and..
get(redirectOpts);

don't know too much why since the original opts with proxy setting are re-copied in redirectOpts, it should work.

I saw that in the latest versions of Download, they added code to to redirects themselves ( instead of setting followRedirect)

Thanks for your reply.

**Comment by lathil** [comment]
I had a look at what is hapenning with WireShark, the redirects are there but not due to Got.I close the issue
