### ISSUE TITLE
TimeoutError: Timeout awaiting 'request'

### ISSUE THREAD

**Issue by DenisKrsk** [sindresorhus/got#699]
Hey. With a small load there are no problems. But concurrent 300 requests, estimated using ~1500 this error occurs.

const  got  =  require ( 'got' );
const  ProxyAgent  =  require ('proxy-agent');

(async function(){
    var startTime = Date.now()
    var response = await got("https://gmail.com",
        {   
            timeout: 4000, // 1000 => 6329; 2000 => 9232; 3000 => 12266; 4000 => 15291
            retries:0,
            decompress:false,
            agent: new ProxyAgent("https://192.168.1.11")
        }).catch(e=>{console.log(e)});
    console.log(Date.now() - startTime);
})();

`events.js:167
      throw er; // Unhandled 'error' event
      ^

TimeoutError: Timeout awaiting 'request' for 4000ms
    at ClientRequest.request.once.error (D:\bots\node\parser\node_modules\got\so
urce\request-as-event-emitter.js:163:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.origin.emit.args (D:\bots\node\parser\node_modules\@szmarcz
ak\http-timer\source\index.js:37:11)
    at Immediate.timeoutHandler (D:\bots\node\parser\node_modules\got\source\uti
ls\timed-out.js:63:11)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at ClientRequest.request.once.error (D:\bots\node\parser\node_modules\got\so
urce\request-as-event-emitter.js:169:14)
    at Object.onceWrapper (events.js:273:13)
    [... lines matching original stack trace ...]
    at processImmediate (timers.js:658:5)`

**Comment by ash0080** [comment]
same issue
```
(node:3282) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: Timeout awaiting 'request' for 10000ms
(node:3282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
still happen even set 
retry:0
