### ISSUE TITLE
Better Error handling

### ISSUE THREAD

**Issue by iyobo** [sindresorhus/got#715]
Got needs better error handling.
Whenever there is an error, it is basically impossible to tell which call is actually erroring out because this is basically what we get.

```
UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:5984
    at ClientRequest.req.once.err (.../node_modules/got/index.js:111:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by szmarczak** [comment]
Could you please fill the template out? The issue lacks many information, which could be very helpful for us to solve the issue.

> Got needs better error handling.

On what basis you say so? Do you catch the errors properly? If we could reproduce the issue, that'd be great :)
