### ISSUE TITLE
package.json installation via git doesn't work

### ISSUE THREAD

**Issue by kairusds** [sindresorhus/got#749]
#### Describe the bug

 - Node.js version: 8.15.1
 - OS & version: (Unclear, Heroku Linux)

Installing the `got` module from the master branch doesn't work.

#### Actual behavior

...

#### Expected behavior

...

#### Code to reproduce
`package.json`
```
"dependencies": {
  "got": "github:sindresorhus/got#master"
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
We can't help, the issue is not on our side.

I have checked - installing from github works.

**Comment by kairusds** [comment]
how so? i tried doing any workarounds i can think of but it won't install

**Comment by szmarczak** [comment]
Can you paste the full console output?

**Comment by kairusds** [comment]
it says `Cannot find module "got"` and the rest are thrown  exceptions by module.js

**Comment by szmarczak** [comment]
> Can you paste the full console output?

This is not a full console output.

**Comment by josenobile** [comment]
0.
```
node --version
v12.10.0

```
```
npm --version
6.10.3
```

1. 
```
"dependencies": {
    "got": "sindresorhus/got"
  }
```

2.

```
npm install --production --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--production',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.10.3
npm info using node@v12.10.0
npm verb npm-session ba51e650439ad796
npm info lifecycle lqip-service@1.0.0~preinstall: lqip-service@1.0.0
npm timing stage:loadCurrentTree Completed in 7ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
npm info lifecycle got@9.6.0~prepack: got@9.6.0
npm info lifecycle got@9.6.0~postpack: got@9.6.0
npm http fetch GET 200 https://registry.npmjs.org/cacheable-lookup 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@types%2ftough-cookie 192ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/get-stream 186ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 117ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 189ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/duplexer3 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@types%2fcacheable-request 197ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cacheable-request 194ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lowercase-keys 194ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/p-cancelable 58ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/type-fest 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/to-readable-stream 60ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/responselike 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@sindresorhus%2fis 461ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@szmarczak%2fhttp-timer 825ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/defer-to-connect 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@types%2fkeyv 31ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@types%2fresponselike 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@types%2fhttp-cache-semantics 49ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@types%2fnode 52ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/keyv 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json-buffer 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/clone-response 36ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/http-cache-semantics 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/normalize-url 46ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/end-of-stream 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/once 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 49ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7589ms
npm timing stage:loadIdealTree Completed in 7605ms
npm timing stage:generateActionsToTake Completed in 8ms
npm verb correctMkdir C:\Users\josen\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\josen\AppData\Roaming\npm-cache\_locks\staging-1c28a674b4240aad.lock for C:\wamp\www\lqip-service\app\node_modules\.staging
npm timing audit submit Completed in 201ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 201ms
npm timing audit body Completed in 0ms
npm info lifecycle got@9.6.0~prepack: got@9.6.0
npm info lifecycle got@9.6.0~postpack: got@9.6.0
npm timing action:extract Completed in 14899ms
npm timing action:finalize Completed in 117ms
npm timing action:refresh-package-json Completed in 117ms
npm info lifecycle @sindresorhus/is@0.17.1~preinstall: @sindresorhus/is@0.17.1
npm info lifecycle @types/http-cache-semantics@4.0.0~preinstall: @types/http-cache-semantics@4.0.0
npm info lifecycle @types/node@12.7.4~preinstall: @types/node@12.7.4
npm info lifecycle @types/keyv@3.1.0~preinstall: @types/keyv@3.1.0
npm info lifecycle @types/responselike@1.0.0~preinstall: @types/responselike@1.0.0
npm info lifecycle @types/cacheable-request@6.0.1~preinstall: @types/cacheable-request@6.0.1
npm info lifecycle @types/tough-cookie@2.3.5~preinstall: @types/tough-cookie@2.3.5
npm info lifecycle mimic-response@1.0.1~preinstall: mimic-response@1.0.1
npm info lifecycle clone-response@1.0.2~preinstall: clone-response@1.0.2
npm info lifecycle defer-to-connect@1.0.2~preinstall: defer-to-connect@1.0.2
npm info lifecycle @szmarczak/http-timer@2.0.0~preinstall: @szmarczak/http-timer@2.0.0
npm info lifecycle duplexer3@0.1.4~preinstall: duplexer3@0.1.4
npm info lifecycle http-cache-semantics@4.0.3~preinstall: http-cache-semantics@4.0.3
npm info lifecycle json-buffer@3.0.0~preinstall: json-buffer@3.0.0
npm info lifecycle keyv@3.1.0~preinstall: keyv@3.1.0
npm info lifecycle cacheable-lookup@0.2.1~preinstall: cacheable-lookup@0.2.1
npm info lifecycle lowercase-keys@2.0.0~preinstall: lowercase-keys@2.0.0
npm info lifecycle mimic-response@2.0.0~preinstall: mimic-response@2.0.0
npm info lifecycle decompress-response@4.2.1~preinstall: decompress-response@4.2.1
npm info lifecycle normalize-url@4.3.0~preinstall: normalize-url@4.3.0
npm info lifecycle p-cancelable@2.0.0~preinstall: p-cancelable@2.0.0
npm info lifecycle lowercase-keys@1.0.1~preinstall: lowercase-keys@1.0.1
npm info lifecycle responselike@1.0.2~preinstall: responselike@1.0.2
npm info lifecycle to-readable-stream@2.1.0~preinstall: to-readable-stream@2.1.0
npm info lifecycle type-fest@0.5.2~preinstall: type-fest@0.5.2
npm info lifecycle wrappy@1.0.2~preinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~preinstall: once@1.4.0
npm info lifecycle end-of-stream@1.4.1~preinstall: end-of-stream@1.4.1
npm info lifecycle pump@3.0.0~preinstall: pump@3.0.0
npm info lifecycle get-stream@5.1.0~preinstall: get-stream@5.1.0
npm info lifecycle cacheable-request@6.1.0~preinstall: cacheable-request@6.1.0
npm info lifecycle got@9.6.0~preinstall: got@9.6.0
npm timing action:preinstall Completed in 7ms
npm info linkStuff @sindresorhus/is@0.17.1
npm info linkStuff @types/http-cache-semantics@4.0.0
npm info linkStuff @types/node@12.7.4
npm info linkStuff @types/keyv@3.1.0
npm info linkStuff @types/responselike@1.0.0
npm info linkStuff @types/cacheable-request@6.0.1
npm info linkStuff @types/tough-cookie@2.3.5
npm info linkStuff mimic-response@1.0.1
npm info linkStuff clone-response@1.0.2
npm info linkStuff defer-to-connect@1.0.2
npm info linkStuff @szmarczak/http-timer@2.0.0
npm info linkStuff duplexer3@0.1.4
npm info linkStuff http-cache-semantics@4.0.3
npm info linkStuff json-buffer@3.0.0
npm info linkStuff keyv@3.1.0
npm info linkStuff cacheable-lookup@0.2.1
npm info linkStuff lowercase-keys@2.0.0
npm info linkStuff mimic-response@2.0.0
npm info linkStuff decompress-response@4.2.1
npm info linkStuff normalize-url@4.3.0
npm info linkStuff p-cancelable@2.0.0
npm info linkStuff lowercase-keys@1.0.1
npm info linkStuff responselike@1.0.2
npm info linkStuff to-readable-stream@2.1.0
npm info linkStuff type-fest@0.5.2
npm info linkStuff wrappy@1.0.2
npm info linkStuff once@1.4.0
npm info linkStuff end-of-stream@1.4.1
npm info linkStuff pump@3.0.0
npm info linkStuff get-stream@5.1.0
npm info linkStuff cacheable-request@6.1.0
npm info linkStuff got@9.6.0
npm timing action:build Completed in 9ms
npm info lifecycle @sindresorhus/is@0.17.1~install: @sindresorhus/is@0.17.1
npm info lifecycle @types/http-cache-semantics@4.0.0~install: @types/http-cache-semantics@4.0.0
npm info lifecycle @types/node@12.7.4~install: @types/node@12.7.4
npm info lifecycle @types/keyv@3.1.0~install: @types/keyv@3.1.0
npm info lifecycle @types/responselike@1.0.0~install: @types/responselike@1.0.0
npm info lifecycle @types/cacheable-request@6.0.1~install: @types/cacheable-request@6.0.1
npm info lifecycle @types/tough-cookie@2.3.5~install: @types/tough-cookie@2.3.5
npm info lifecycle mimic-response@1.0.1~install: mimic-response@1.0.1
npm info lifecycle clone-response@1.0.2~install: clone-response@1.0.2
npm info lifecycle defer-to-connect@1.0.2~install: defer-to-connect@1.0.2
npm info lifecycle @szmarczak/http-timer@2.0.0~install: @szmarczak/http-timer@2.0.0
npm info lifecycle duplexer3@0.1.4~install: duplexer3@0.1.4
npm info lifecycle http-cache-semantics@4.0.3~install: http-cache-semantics@4.0.3
npm info lifecycle json-buffer@3.0.0~install: json-buffer@3.0.0
npm info lifecycle keyv@3.1.0~install: keyv@3.1.0
npm info lifecycle cacheable-lookup@0.2.1~install: cacheable-lookup@0.2.1
npm info lifecycle lowercase-keys@2.0.0~install: lowercase-keys@2.0.0
npm info lifecycle mimic-response@2.0.0~install: mimic-response@2.0.0
npm info lifecycle decompress-response@4.2.1~install: decompress-response@4.2.1
npm info lifecycle normalize-url@4.3.0~install: normalize-url@4.3.0
npm info lifecycle p-cancelable@2.0.0~install: p-cancelable@2.0.0
npm info lifecycle lowercase-keys@1.0.1~install: lowercase-keys@1.0.1
npm info lifecycle responselike@1.0.2~install: responselike@1.0.2
npm info lifecycle to-readable-stream@2.1.0~install: to-readable-stream@2.1.0
npm info lifecycle type-fest@0.5.2~install: type-fest@0.5.2
npm info lifecycle wrappy@1.0.2~install: wrappy@1.0.2
npm info lifecycle once@1.4.0~install: once@1.4.0
npm info lifecycle end-of-stream@1.4.1~install: end-of-stream@1.4.1
npm info lifecycle pump@3.0.0~install: pump@3.0.0
npm info lifecycle get-stream@5.1.0~install: get-stream@5.1.0
npm info lifecycle cacheable-request@6.1.0~install: cacheable-request@6.1.0
npm info lifecycle got@9.6.0~install: got@9.6.0
npm timing action:install Completed in 8ms
npm info lifecycle @sindresorhus/is@0.17.1~postinstall: @sindresorhus/is@0.17.1
npm info lifecycle @types/http-cache-semantics@4.0.0~postinstall: @types/http-cache-semantics@4.0.0
npm info lifecycle @types/node@12.7.4~postinstall: @types/node@12.7.4
npm info lifecycle @types/keyv@3.1.0~postinstall: @types/keyv@3.1.0
npm info lifecycle @types/responselike@1.0.0~postinstall: @types/responselike@1.0.0
npm info lifecycle @types/cacheable-request@6.0.1~postinstall: @types/cacheable-request@6.0.1
npm info lifecycle @types/tough-cookie@2.3.5~postinstall: @types/tough-cookie@2.3.5
npm info lifecycle mimic-response@1.0.1~postinstall: mimic-response@1.0.1
npm info lifecycle clone-response@1.0.2~postinstall: clone-response@1.0.2
npm info lifecycle defer-to-connect@1.0.2~postinstall: defer-to-connect@1.0.2
npm info lifecycle @szmarczak/http-timer@2.0.0~postinstall: @szmarczak/http-timer@2.0.0
npm info lifecycle duplexer3@0.1.4~postinstall: duplexer3@0.1.4
npm info lifecycle http-cache-semantics@4.0.3~postinstall: http-cache-semantics@4.0.3
npm info lifecycle json-buffer@3.0.0~postinstall: json-buffer@3.0.0
npm info lifecycle keyv@3.1.0~postinstall: keyv@3.1.0
npm info lifecycle cacheable-lookup@0.2.1~postinstall: cacheable-lookup@0.2.1
npm info lifecycle lowercase-keys@2.0.0~postinstall: lowercase-keys@2.0.0
npm info lifecycle mimic-response@2.0.0~postinstall: mimic-response@2.0.0
npm info lifecycle decompress-response@4.2.1~postinstall: decompress-response@4.2.1
npm info lifecycle normalize-url@4.3.0~postinstall: normalize-url@4.3.0
npm info lifecycle p-cancelable@2.0.0~postinstall: p-cancelable@2.0.0
npm info lifecycle lowercase-keys@1.0.1~postinstall: lowercase-keys@1.0.1
npm info lifecycle responselike@1.0.2~postinstall: responselike@1.0.2
npm info lifecycle to-readable-stream@2.1.0~postinstall: to-readable-stream@2.1.0
npm info lifecycle type-fest@0.5.2~postinstall: type-fest@0.5.2
npm info lifecycle wrappy@1.0.2~postinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~postinstall: once@1.4.0
npm info lifecycle end-of-stream@1.4.1~postinstall: end-of-stream@1.4.1
npm info lifecycle pump@3.0.0~postinstall: pump@3.0.0
npm info lifecycle get-stream@5.1.0~postinstall: get-stream@5.1.0
npm info lifecycle cacheable-request@6.1.0~postinstall: cacheable-request@6.1.0
npm info lifecycle got@9.6.0~postinstall: got@9.6.0
npm timing action:postinstall Completed in 12ms
npm verb unlock done using C:\Users\josen\AppData\Roaming\npm-cache\_locks\staging-1c28a674b4240aad.lock for C:\wamp\www\lqip-service\app\node_modules\.staging
npm timing stage:executeActions Completed in 15194ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm info linkStuff lqip-service@1.0.0
npm info lifecycle lqip-service@1.0.0~install: lqip-service@1.0.0
npm info lifecycle lqip-service@1.0.0~postinstall: lqip-service@1.0.0
npm timing stage:runTopLevelLifecycles Completed in 22855ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm notice created a lockfile as package-lock.json. You should commit this file.
npm info lifecycle undefined~postshrinkwrap: undefined
added 32 packages from 53 contributors and audited 49 packages in 22.909s
found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 23302ms
npm info ok

```

3. 
cat test.js
require('got')

node test.js
```
internal/modules/cjs/loader.js:296
      throw err;
      ^

Error: Cannot find module 'C:\wamp\www\lqip-service\app\node_modules\got\dist'. Please verify that the package.json has a valid "main" entry
?[90m    at tryPackage (internal/modules/cjs/loader.js:288:19)?[39m
?[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:515:18)?[39m
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:759:27)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:677:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:830:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:68:18)?[39m
    at Object.<anonymous> (C:\wamp\www\lqip-service\app\test.js:1:1)
?[90m    at Module._compile (internal/modules/cjs/loader.js:936:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:790:32)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  path: ?[32m'C:\\wamp\\www\\lqip-service\\app\\node_modules\\got\\package.json'?[39m,
  requestPath: ?[32m'got'?[39m


```

**Comment by szmarczak** [comment]
Indeed. `github:sindresorhus/got#master` doesn't work but `github:sindresorhus/got#v9.6.0` works. That's because the `dist` directory doesn't exist in the GitHub tree. **You need to build Got on your own.**

I think @sindresorhus might have considered that but didn't decide to include it, because of these reasons:

1. Some people would edit those files instead of the one included in `source/*`.
2. Every contributor would need to commit **after** building. This would be annoying when all tests pass but you forgot to put a semicolon.
3. Automatic builds would require an additional commit per each PR. So it's better to use an alpha NPM version instead of the GitHub one.

There is no alpha version as for now.

**Comment by yovanoc** [comment]
You could "hack" like that : 

![image](https://user-images.githubusercontent.com/7302317/64478978-b7d2b700-d1b0-11e9-9df3-4ee581031968.png)

Ignore the `prisma2 generate` but build got inside the postinstall script and it's working great

**Comment by sindresorhus** [comment]
I tried to change to use the `prepare` run-script instead, which is documented to work on Git install, but I could still not get it to install correctly. It just creates a `dist` folder with the package.json. Something weird is going on. https://github.com/sindresorhus/got/commit/c59342868ad5e17b500da13ef667f20b06e29c29

**Comment by sindresorhus** [comment]
There's now an alpha version out for v10: https://github.com/sindresorhus/got/releases/tag/v10.0.0-alpha.1
