### ISSUE TITLE
HPE_HEADER_OVERFLOW

### ISSUE THREAD

**Issue by gajus** [sindresorhus/got#778]
#### Describe the bug

 - Node.js version: v11.3.0
 - OS & version: OSX, Version 73

#### Actual behavior

Throws HPE_HEADER_OVERFLOW error.

#### Expected behavior

No error.

#### Code to reproduce

```js
got('https://www.flickr.com/');

```

#### Actual error

```
{ RequestError: Parse Error
    at ClientRequest.request.once.error (/Users/gajus/Documents/dev/gitspo/gitspo-agent/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.origin.emit.args (/Users/gajus/Documents/dev/gitspo/gitspo-agent/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketOnData (_http_client.js:455:9)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:122:17)
  name: 'RequestError',
  code: 'HPE_HEADER_OVERFLOW',
  host: 'flickr.com',
  hostname: 'www.flickr.com',
  method: 'GET',
  path: '/',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://www.flickr.com/',
  gotOptions:
   { path: '/',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'flickr.com',
     port: null,
     hostname: 'www.flickr.com',
     hash: '',
     search: '',
     query: null,
     pathname: '/',
     href: 'https://www.flickr.com/',
     retry:
      { retries: [Function],
        methods: Set { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
        statusCodes: Set { 408, 413, 429, 500, 502, 503, 504 },
        errorCodes:
         Set {
           'ETIMEDOUT',
           'ECONNRESET',
           'EADDRINUSE',
           'ECONNREFUSED',
           'EPIPE',
           'ENOTFOUND',
           'ENETUNREACH',
           'EAI_AGAIN' } },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate' },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: false,
     cache: false,
     useElectronNet: false,
     method: 'GET' } }

```

**Comment by szmarczak** [comment]
This is not actually a Got failure: https://stackoverflow.com/a/35330480

**Comment by szmarczak** [comment]
I don't think we can solve this without setting proper node arguments first.

**Comment by szmarczak** [comment]
https://nodejs.org/api/cli.html#cli_max_http_header_size_size
