### ISSUE TITLE
Wired behaviors when set retry to 0

### ISSUE THREAD

**Issue by ash0080** [sindresorhus/got#856]
#### Describe the bug

 - Node.js version:  8.9.0 / 10.16.0
 - OS & version:  OSX 10.14.6
 - got 9.6.0

POST with retry= 0 
when error happen, sometimes, it

will throw uncatched 'socket hang up' error   /  Nodejs. 8.9.0 
will throw ' Client network socket disconnected before secure TLS connection was established'  / Nodejs 10.16.0

#### Checklist

- [ X ] I have read the documentation.
- [ X ] I have tried my code with the latest version of Node.js and Got.

**Comment by ash0080** [comment]
sorry, forget to say,  I use retry 0 because this issue happen again #631

**Comment by szmarczak** [comment]
Some code to reproduce? Try running the master branch: `npm install sindresorhus/got#master`

**Comment by ash0080** [comment]
Sorry, the code itself is nothing special,
but I use a TOR node as proxy agent,
so the error could be reproduced easier.

You can try default retry setting first, mostly, it will throw an unhandled promise warning even if I wrap await got(...)  in try... catch

then set retry =0 could dismiss the unhandled promise, but has high probability to throw uncatched ‘socket hang up’ error

**Comment by szmarczak** [comment]
Did you try running the master version?

**Comment by ash0080** [comment]
'===========================================================================
<1> LoginError: [OtherError] socket hang up
---------------------------------------------------------------------------
at module.exports (/Volumes/Root/Users/Elvis/Desktop/buybuybuy/project/packages/LoginService/stores/shilladfs/login.js:63:24)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
===========================================================================
<2*> RequestError: socket hang up
---------------------------------------------------------------------------
at ClientRequest.request.once.error (/Volumes/Root/Users/Elvis/Desktop/buybuybuy/project/packages/LoginService/node_modules/got/source/request-as-event-emitter.js:178:14)
at Object.onceWrapper (events.js:315:30)
at emitOne (events.js:121:20)
at ClientRequest.emit (events.js:211:7)
at ClientRequest.origin.emit.args (/Volumes/Root/Users/Elvis/Desktop/buybuybuy/project/packages/LoginService/node_modules/@szmarczak/http-timer/source/index.js:37:11)
at TLSSocket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
at TLSSocket.emit (events.js:211:7)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
===========================================================================',

a captured one, 
wish to help

**Comment by szmarczak** [comment]
> Did you try running the master version?

**Comment by ash0080** [comment]
Tested, thought I haven't got a hang out error, but 
the master version seems  worse,

blue means timeout
![屏幕快照 2019-08-12 16 30 52](https://user-images.githubusercontent.com/2803210/62853439-efb81d00-bd1e-11e9-8210-8a319fa9c081.png)

**Comment by ash0080** [comment]
Sorry, finally found it's a bug from my code, the progress timed out before got finished
