### ISSUE TITLE
Memory leak when using a self-signed certificate

### ISSUE THREAD

**Issue by darksabrefr** [sindresorhus/got#962]
Node complains about an event emitter memory leak when use got 10 with an https agent (the native one or keep-alive-agent, no matter) to request https adresses with self-signed certificate (and so with `rejectUnauthorized` set to `false`).
I don't really know if the problem is located in got, in http-timer or in defer-to-connect but it seems to be a got internal issue. I think the socket in this context never emit `secureConnect` event so the main issue should be here : https://github.com/szmarczak/defer-to-connect/blob/master/source/index.ts#L33

 - Node.js version: 13.2.0
 - OS & version: Ubuntu 19.10

#### Actual behavior

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 secureConnect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:268:17)
    at TLSSocket.addListener (events.js:284:10)
    at TLSSocket.Readable.on (_stream_readable.js:884:35)
    at TLSSocket.once (events.js:315:8)
    at onConnect (/home/clement/dev/data-import/node_modules/defer-to-connect/dist/index.js:25:24)
    at Object.deferToConnect [as default] (/home/clement/dev/data-import/node_modules/defer-to-connect/dist/index.js:33:9)
    at ClientRequest.<anonymous> (/home/clement/dev/data-import/node_modules/@szmarczak/http-timer/dist/index.js:52:35)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/home/clement/dev/data-import/node_modules/@szmarczak/http-timer/dist/index.js:40:20)
    at tickOnSocket (_http_client.js:685:7)
    at onSocketNT (_http_client.js:724:5)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

#### Code to reproduce

You will need an http server with a self-signed certificate. To get the full stack associated with this warning, use `node --trace-warnings --stack-trace-limit=30`. I output the secureConnect timing for each request because it seems important to note the first is defined and the others are undefined in the bug context. Without the bug context (with an https server having a real certificate or without agent), all of these are defined.
```js
'use strict';

const got = require('got');
const {Agent} = require('https');

const gotOptions = {
	agent: new Agent({maxSockets: 1}),
	throwHttpErrors: false,
	rejectUnauthorized: false
};
const requests = [];
for (let i = 0; i < 12 ; i++) {
	requests.push(got('https://localhost/api/', gotOptions))
}
Promise.all(requests).then(results => {
	console.log(results.map(r => r.timings.secureConnect));
});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
I think it happens only when using a self-signed certificate, because `socket.authorized` is `false` in that case: https://nodejs.org/api/tls.html#tls_event_secureconnect

Have you tried with `https://google.com`?

**Comment by darksabrefr** [comment]
Yes, I have tried with `https://google.com`, there's no problem with regular certificates, only with self-signed ones.

**Comment by darksabrefr** [comment]
Thank you @szmarczak for the fast fix, I can confirm that the bug disappeared.
