### ISSUE TITLE
Unhandled premature close after timeout

### ISSUE THREAD

**Issue by xPaw** [sindresorhus/got#975]
```js
const got = require('got');

process.on('unhandledRejection', console.log);

(async () => {
    const promise = got('http://localhost/sleep.php', {
        timeout: 1000,
        retry: 0,
    });

    try {
        await promise;
    } catch (error) {
        console.log('Caught:', error);
    }

    await new Promise(resolve => setTimeout(resolve, 2000));
})();
```

```
Caught: GotError: Timeout awaiting 'request' for 1000ms
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:61:15)
    at IncomingMessage.emit (events.js:219:5)
    at IncomingMessage.origin.emit (D:\GitHub\thelounge\node_modules\@szmarczak\http-timer\dist\index.js:40:20)
    at TLSSocket.socketCloseListener (_http_client.js:377:11)
    at TLSSocket.emit (events.js:224:7)
    at net.js:666:12
    at TCP.done (_tls_wrap.js:488:7) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
```

I was testing against a php script which flushes some data and then sleeps:
```php
<?php
for($i = 0; $i < 10000; $i++) echo 'test';
flush();
sleep(2);
echo 'end';
```

**Comment by szmarczak** [comment]
I can reproduce this: https://runkit.com/szmarczak/5dec2a32477b9a001a784841

**Comment by szmarczak** [comment]
I'll soon push a fix. This is caused by `stream.pipeline(...)` which detects sudden stream close.
